import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

const appPath = "src/client/App.tsx";

describe("video creation layout source", () => {
  it("uses one product creative workspace for both image and video creation", async () => {
    const source = await readFile(appPath, "utf8");
    const appSource = source.slice(source.indexOf("export function App()"), source.indexOf("function AppLanguageSwitcher"));
    const videoCase = appSource.slice(appSource.indexOf('case "video"'), appSource.indexOf('case "image"'));
    const imageCase = appSource.slice(appSource.indexOf('case "image"'), appSource.indexOf('case "ledger"'));
    const workspaceSource = source.slice(source.indexOf("function ProductCreationWorkspace"), source.indexOf("function ProductCreationProductLibrary"));
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductCreationProductLibrary"));

    expect(videoCase).toContain('mode="video"');
    expect(imageCase).toContain('mode="image"');
    expect(imageCase).toContain("<ProductCreationWorkspace");
    expect(imageCase).not.toContain('tApp("image.empty")');
    expect(workspaceSource).toContain("mode: ProductCreativeWorkspaceMode;");
    expect(composerSource).toContain("buildProductCreativeWorkspace");
    expect(composerSource).toContain("ProductCreativeWorkspacePanel");
    expect(composerSource).toContain("ProductImageAssetPanel");
    expect(composerSource).toContain("handleGenerateProductImages");
  });

  it("renders video creation as product library plus operation workspace instead of a top control bar", async () => {
    const source = await readFile(appPath, "utf8");
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductComposerReferenceTray"));

    expect(composerSource).toContain("video-workspace-shell");
    expect(composerSource).toContain("h-[100dvh] max-h-[100dvh] min-h-0 grid-rows-[minmax(0,1fr)]");
    expect(composerSource).toContain("transition-[grid-template-columns] duration-200");
    expect(composerSource).toContain("min-[900px]:grid-cols-[var(--product-library-column-width)_minmax(0,1fr)]");
    expect(composerSource).toContain('style={{ "--product-library-column-width": `${productLibraryColumnWidth}px` } as CSSProperties}');
    expect(composerSource).toContain("PRODUCT_LIBRARY_DEFAULT_WIDTH");
    expect(composerSource).toContain("PRODUCT_LIBRARY_COLLAPSED_WIDTH");
    expect(composerSource).not.toContain("PRODUCT_LIBRARY_COLLAPSE_SNAP_WIDTH");
    expect(composerSource).not.toContain("PRODUCT_LIBRARY_MIN_WIDTH");
    expect(composerSource).not.toContain("PRODUCT_LIBRARY_MAX_WIDTH");
    expect(composerSource).not.toContain("min-[900px]:grid-cols-[292px_minmax(0,1fr)]");
    expect(composerSource).toContain("productLibraryCollapsed");
    expect(composerSource).toContain("productLibraryColumnWidth");
    expect(composerSource).not.toContain("const [productLibraryWidth");
    expect(composerSource).not.toContain("handleProductLibraryResizeStart");
    expect(composerSource).not.toContain("handleProductLibraryResizeKeyDown");
    expect(composerSource).not.toContain('role="separator"');
    expect(composerSource).not.toContain('aria-orientation="vertical"');
    expect(composerSource).not.toContain("aria-valuenow={productLibraryColumnWidth}");
    expect(composerSource).toContain("video-product-library-collapse-rail");
    expect(composerSource).toContain("video-product-library-collapse-button");
    expect(composerSource).toContain("transition-[left,color]");
    expect(composerSource).not.toContain("video-product-library-resizer");
    expect(composerSource).not.toContain("productLibraryResizing");
    expect(composerSource).not.toContain("setProductLibraryResizing");
    expect(composerSource).not.toContain("MoveHorizontal");
    expect(composerSource).toContain("cursor-pointer");
    expect(composerSource).toContain("opacity-0");
    expect(composerSource).toContain("group-hover:opacity-100");
    expect(composerSource).toContain('aria-label={productLibraryCollapsed ? tVideo("productLibrary.expand") : tVideo("productLibrary.collapse")}');
    expect(composerSource).toContain('title={productLibraryCollapsed ? tVideo("productLibrary.expand") : tVideo("productLibrary.collapse")}');
    expect(composerSource).toContain("onClick={() => setProductLibraryCollapsed((collapsed) => !collapsed)}");
    expect(composerSource).not.toContain("拖动调整商品库宽度");
    expect(composerSource).toContain("video-product-library-column");
    expect(composerSource).toContain("video-operation-column");
    expect(composerSource).toContain("grid content-start gap-3");
    expect(composerSource).not.toContain("grid min-h-full content-start gap-3");
    expect(composerSource).toContain("video-generation-controls compact-generation-controls");
    expect(composerSource).toContain("py-2");
    expect(composerSource).toContain("model-scheme-control");
    expect(composerSource).toContain("model-scheme-chip-row");
    expect(composerSource).toContain("min-[1180px]:col-span-7");
    expect(composerSource).toContain("overflow-visible");
    expect(composerSource).toContain("ModelSchemeChip");
    expect(composerSource).toContain("{schemeSummary}");
    expect(composerSource).toContain('label={tVideo("controls.resolution")}');
    expect(composerSource).toContain("videoResolutionOptions");
    expect(composerSource).toContain("videoResolutionLabel");
    expect(composerSource).toContain("selectedVideoResolution");
    expect(composerSource).toContain("onVideoResolutionChange");
    expect(composerSource).toContain('label={tVideo("controls.aspectRatio")}');
    expect(composerSource).toContain("videoAspectRatioOptions");
    expect(composerSource).toContain("videoAspectRatioLabel");
    expect(composerSource).toContain("selectedVideoAspectRatio");
    expect(composerSource).toContain("onVideoAspectRatioChange");
    expect(composerSource).toContain('const languageOptions: FinalVideoLanguage[] = ["ja", "zh", "en"]');
    expect(source).toContain('finalLanguageLabel(finalLanguage, tVideo)');
    expect(composerSource).toContain('density="compact"');
    expect(composerSource).toContain("generation-status-message");
    expect(composerSource).toContain("video-generate-summary");
    expect(composerSource).toContain("{generateVideoSummary}");
    expect(composerSource).toContain("tracking-0");
    expect(composerSource).toContain("whitespace-normal");
    expect(composerSource).toContain("break-words");
    expect(composerSource).not.toContain("video-generate-summary min-w-0 truncate");
    expect(composerSource).not.toContain("generateVideoSummaryItems.map");
    expect(composerSource).not.toContain("video-generate-summary-item");
    expect(composerSource).not.toContain("video-generate-summary-separator");
    expect(composerSource).not.toContain("gap-x-2 gap-y-1");
    expect(composerSource).toContain("video-generate-status-center");
    expect(composerSource).toContain("justify-center text-center");
    expect(composerSource).toContain("min-[900px]:grid-cols-[minmax(0,1fr)_minmax(220px,auto)_minmax(220px,320px)]");
    expect(composerSource).not.toContain("subtitle={generateVideoSummary}");
    expect(composerSource).not.toContain("model-scheme-summary min-w-0 whitespace-normal break-words");
    expect(composerSource).not.toContain("model-scheme-summary min-w-0 truncate");
    expect(composerSource).not.toContain("<div className=\"min-w-0 truncate text-xs font-bold text-[var(--muted)]\">{schemeSummary}</div>");
    expect(composerSource).toContain("resolution: selectedVideoResolution");
    expect(composerSource).toContain("aspectRatio: selectedVideoAspectRatio");
    expect(composerSource).toContain("ProductCreationProductLibrary");
    expect(composerSource).toContain("ProductCreationOperationWorkspace");
    expect(composerSource).toContain("collapsed={productLibraryCollapsed}");
    expect(composerSource).toContain("productLibrarySearchQuery");
    expect(composerSource).toContain("filterProductLibraryProducts(productOptions, productLibrarySearchQuery");
    expect(composerSource).toContain("product-library-search");
    expect(composerSource).toContain('aria-label={tVideo("productLibrary.search")}');
    expect(composerSource).toContain('placeholder={tVideo("productLibrary.search")}');
    expect(composerSource).not.toContain("搜索商品 / SKU");
    expect(composerSource).toContain("product-library-scroll min-h-0 overflow-y-auto");
    expect(composerSource).toContain('{tVideo("productLibrary.noMatches")}');
    expect(composerSource).toContain('{tVideo("productLibrary.clearSearch")}');
    expect(composerSource).not.toContain("手动填写或粘贴商品资料");
    expect(composerSource).not.toContain("footer={");
    expect(composerSource).not.toContain("product-control-bar");
    expect(composerSource).not.toContain("video-parameter-row grid");
    expect(composerSource).not.toContain("<ProductCreationProductPicker");

    const generateBarIndex = composerSource.indexOf("video-generate-bar");
    const historyPanelIndex = composerSource.indexOf("<VideoHistoryPanel");
    expect(generateBarIndex).toBeGreaterThan(-1);
    expect(historyPanelIndex).toBeGreaterThan(-1);
    expect(generateBarIndex).toBeLessThan(historyPanelIndex);
  });

  it("localizes video workspace UI without translating product data fields", async () => {
    const source = await readFile(appPath, "utf8");
    const appSource = source.slice(source.indexOf("export function App()"), source.indexOf("function AppLanguageSwitcher"));
    const workspaceSource = source.slice(source.indexOf("function ProductCreationWorkspace"), source.indexOf("function ProductLibraryHome"));
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductCreationProductLibrary"));
    const librarySource = source.slice(source.indexOf("function ProductCreationProductLibrary"), source.indexOf("function ProductCreationOperationWorkspace"));
    const operationSource = source.slice(source.indexOf("function ProductCreationOperationWorkspace"), source.indexOf("function ProductComposerReferenceTray"));
    const referenceTraySource = source.slice(source.indexOf("function ProductComposerReferenceTray"), source.indexOf("function StoryboardComposerPanel"));
    const storyboardPanelSource = source.slice(source.indexOf("function StoryboardComposerPanel"), source.indexOf("function VideoHistoryPanel"));
    const historyPanelSource = source.slice(source.indexOf("function VideoHistoryPanel"), source.indexOf("function ProductLibraryHome"));
    const referenceFigureSource = source.slice(source.indexOf("function ReferenceImageFigure"), source.indexOf("function ReferenceImagePreviewDialog"));
    const referencePreviewSource = source.slice(source.indexOf("function ReferenceImagePreviewDialog"), source.indexOf("function ProductEntryModeButton"));
    const helperSource = source.slice(source.indexOf("function localizedVideoLabel"), source.indexOf("function jobStatusTone"));

    expect(appSource).toContain("localizedDefaultStoryboardDraft(defaultVideoTemplate, defaultVideoDurationSeconds, appLocale)");
    expect(appSource).toContain("localizedDefaultStoryboardDraft(template, duration, appLocale)");
    expect(appSource).toContain("if (storyboardDraftTouched) return;");
    expect(appSource).toContain("[template, duration, appLocale, storyboardDraftTouched]");
    expect(workspaceSource).toContain("appLocale={appLocale}");
    expect(composerSource).toContain('const tVideo = (key: string, options?: Record<string, unknown>) => i18n.t(`app:videoStudio.${key}`, { lng: appLocale, ...options });');
    expect(composerSource).toContain('title={draft.title_ja.trim() || selectedProduct?.title_ja || tVideo("newProduct.title")}');
    expect(composerSource).toContain('value={importText}');
    expect(composerSource).toContain('storyboardDraft={storyboardDraft}');
    expect(composerSource).toContain('draftTitle={draft.title_ja}');
    expect(composerSource).toContain('onToast(tVideo("generate.packageReadyToast"), "ok")');
    expect(composerSource).toContain('onToast(tVideo("generate.queuedToast"), "ok")');
    expect(composerSource).toContain('onToast(tVideo("generate.imageOnlyToast"))');
    expect(composerSource).toContain('{isSubmittingVideo ? tVideo("generate.submitting") : generateVideoButtonLabel}');
    expect(librarySource).toContain("product.title_ja");
    expect(librarySource).toContain('const title = active && draftProductTitle ? draftProductTitle : product.title_ja;');
    expect(librarySource).toContain('title={title}');
    expect(librarySource).toContain('aria-label={`${tVideo("productLibrary.deleteProduct")} ${product.title_ja}`}');
    expect(librarySource).toContain('const tProductStatus = makeAppTranslator("productStatus")');
    expect(librarySource).toContain('const status = productLibraryStatus(product, tProductStatus)');
    expect(operationSource).toContain('{badge ? <Badge className="shrink-0" tone="neutral">{badge}</Badge> : null}');
    expect(referenceTraySource).toContain('tVideo("reference.title")');
    expect(referenceTraySource).toContain('image.original');
    expect(referenceTraySource).toContain('fileName');
    expect(referenceFigureSource).toContain('tVideo("reference.item", { index: index + 1 })');
    expect(referenceFigureSource).toContain('image.original');
    expect(referencePreviewSource).toContain('aria-label={tVideo("reference.previewDialogTitle")}');
    expect(referencePreviewSource).toContain('{image.original}');
    expect(storyboardPanelSource).toContain('tVideo("storyboard.title")');
    expect(storyboardPanelSource).toContain("historyPreview(record.script, appLocale)");
    expect(historyPanelSource).toContain('tVideo("history.title")');
    expect(historyPanelSource).toContain("<VideoHashtagChips tVideo={tVideo}");
    expect(historyPanelSource).toContain("videoDownloadProductContext(product, draft, importText)");
    expect(helperSource).toContain('return tVideo("labels.video", { index: index + 1 });');
    expect(helperSource).toContain('onToast(tVideo("history.tagsCopiedToast"), "ok")');
    expect(helperSource).toContain('function localizedDefaultStoryboardDraft(template: TemplateName, durationSeconds: number, locale: AppLocale): string');
    expect(helperSource).toContain('i18n.t(`app:videoStudio.storyboard.defaultDrafts.${templateKey}`, { lng: locale, returnObjects: true })');
    expect(helperSource).toContain('function storyboardTemplateResourceKey(template: TemplateName): string');

    expect(composerSource).not.toContain('label="模型方案"');
    expect(composerSource).not.toContain('label="视频风格"');
    expect(composerSource).not.toContain('label="视频时长"');
    expect(composerSource).not.toContain('label="成片语言"');
    expect(composerSource).not.toContain('label="生成视频"');
    expect(referenceTraySource).not.toContain(">参考图<");
    expect(referenceFigureSource).not.toContain(">参考图 {index + 1}<");
    expect(referencePreviewSource).not.toContain('aria-label="参考图预览"');
    expect(storyboardPanelSource).not.toContain(">脚本分镜<");
    expect(historyPanelSource).not.toContain(">历史记录<");
  });

  it("keeps concrete model names in the model scheme summary instead of inline panels", async () => {
    const source = await readFile(appPath, "utf8");
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductComposerReferenceTray"));
    const referenceTraySource = source.slice(source.indexOf("function ProductComposerReferenceTray"), source.indexOf("function StoryboardComposerPanel"));
    const storyboardPanelSource = source.slice(source.indexOf("function StoryboardComposerPanel"), source.indexOf("function VideoHistoryPanel"));

    expect(composerSource).toContain("model-scheme-chip-row");
    expect(composerSource).toContain('{ label: tVideo("modelChips.text"), value: localizedModelConfigChoiceLabel(selectedTextModelConfigId, textModelOptions, tVideo) }');
    expect(composerSource).toContain('{ label: tVideo("modelChips.image"), value: localizedModelConfigChoiceLabel(selectedImageModelConfigId, imageModelOptions, tVideo) }');
    expect(composerSource).toContain('{ label: tVideo("modelChips.video"), value: localizedModelConfigChoiceLabel(selectedVideoModelConfigId, videoModelOptions, tVideo) }');
    expect(composerSource).not.toContain('{ label: "文", value: modelConfigChoiceLabel');
    expect(composerSource).not.toContain('{ label: "图", value: modelConfigChoiceLabel');
    expect(composerSource).not.toContain('{ label: "视", value: modelConfigChoiceLabel');
    expect(composerSource).not.toContain("textModelLabel={modelConfigChoiceLabel");
    expect(referenceTraySource).not.toContain("图片模型");
    expect(referenceTraySource).not.toContain("modelConfigChoiceLabel(selectedImageModelConfigId");
    expect(referenceTraySource).not.toContain("selectedImageModelConfigId");
    expect(referenceTraySource).not.toContain("imageModelOptions");
    expect(storyboardPanelSource).not.toContain("文本模型:");
    expect(storyboardPanelSource).not.toContain("textModelLabel");
  });

  it("surfaces concise per-action estimates inside stable video creation action buttons", async () => {
    const source = await readFile(appPath, "utf8");
    const appSource = source.slice(source.indexOf("export function App()"), source.indexOf("function AppLanguageSwitcher"));
    const workspaceSource = source.slice(source.indexOf("function ProductCreationWorkspace"), source.indexOf("function ProductLibraryHome"));
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductCreationProductLibrary"));
    const referenceTraySource = source.slice(source.indexOf("function ProductComposerReferenceTray"), source.indexOf("function StoryboardComposerPanel"));
    const storyboardPanelSource = source.slice(source.indexOf("function StoryboardComposerPanel"), source.indexOf("function VideoHistoryPanel"));
    const actionButtonCostSource = source.slice(source.indexOf("function ActionButtonCost"), source.indexOf("function versionLabel"));

    expect(appSource).toContain('postJson<BillingEstimatesResponse>("/api/billing-estimates"');
    expect(appSource).toContain("videoResolution: selectedVideoResolution");
    expect(appSource).toContain("videoAspectRatio: selectedVideoAspectRatio");
    expect(workspaceSource).toContain("billingEstimates={billingEstimates}");
    expect(composerSource).toContain("billingEstimates?: BillingEstimatesResponse");
    expect(composerSource).toContain('estimate={billingEstimates?.estimates.organizeProduct}');
    expect(composerSource).toContain('estimate={billingEstimates?.estimates.referenceImages}');
    expect(composerSource).toContain('estimate={billingEstimates?.estimates.storyboard}');
    expect(composerSource).toContain('estimate={billingEstimates?.estimates.video}');
    expect(referenceTraySource).toContain("estimate?: BillingActionEstimate");
    expect(referenceTraySource).toContain('<ActionButtonCost tVideo={tVideo} estimate={estimate} />');
    expect(storyboardPanelSource).toContain("estimate?: BillingActionEstimate");
    expect(storyboardPanelSource).toContain('<ActionButtonCost tVideo={tVideo} estimate={estimate} />');
    expect(source).toContain("function ActionButtonCost");
    expect(composerSource).toContain('amountCny={billingEstimates?.estimates.video.upstreamEstimatedCostCny}');
    expect(actionButtonCostSource).toContain('tVideo("costHints.estimated", {');
    expect(actionButtonCostSource).toContain("amountCny?: number");
    expect(actionButtonCostSource).not.toContain('kind === "video"');
    expect(source).not.toContain("costHints.videoEstimated");
    expect(source).not.toContain("costHints.videoDetail");
    expect(source).not.toContain("本次视频预估");
    expect(source).not.toContain("function ActionCostHint");
    expect(source).not.toContain('tVideo("costHints.estimatedCharge"');
    expect(source).not.toContain("预计扣余额");
    expect(source).not.toContain("生成预检");
  });

  it("moves account controls into the left navigation shell and keeps video content full bleed", async () => {
    const source = await readFile(appPath, "utf8");
    const appShellSource = source.slice(source.indexOf("<main"), source.indexOf("function AccountMenu"));
    const brandSource = appShellSource.slice(appShellSource.indexOf("<BrandLogo"), appShellSource.indexOf("<nav"));
    const accountDockSource = appShellSource.slice(appShellSource.indexOf("app-sidebar-account"), appShellSource.indexOf("</aside>"));

    expect(appShellSource).toContain("app-sidebar-account");
    expect(appShellSource).toContain("<AppLanguageSwitcher");
    expect(appShellSource).toContain("collapsed={sidebarCollapsed}");
    expect(brandSource).not.toContain("<AppLanguageSwitcher");
    expect(accountDockSource).toContain("<AccountMenu");
    expect(accountDockSource).toContain("<AppLanguageSwitcher");
    expect(accountDockSource.indexOf("<AccountMenu")).toBeLessThan(accountDockSource.indexOf("<AppLanguageSwitcher"));
    expect(accountDockSource).toContain("{authSession.authEnabled ? (");
    expect(accountDockSource).toContain(") : null}");
    expect(accountDockSource).toContain('sidebarCollapsed ? "grid gap-1.5 px-1.5" : "grid gap-1.5 px-2.5"');
    expect(accountDockSource).not.toContain("grid-cols-[minmax(0,1fr)_36px]");
    expect(appShellSource).toContain("relative flex h-[72px] items-center");
    expect(appShellSource).not.toContain("relative flex h-[72px] items-center border-b");
    expect(appShellSource).toContain("min-[900px]:grid-cols-[232px_minmax(0,1fr)]");
    expect(appShellSource).toContain("relative z-40 hidden h-dvh min-h-0 border-r");
    expect(appShellSource).toContain('sidebarCollapsed ? "w-[56px] overflow-visible" : "w-[232px] overflow-visible"');
    expect(appShellSource).not.toContain('sidebarCollapsed ? "w-[56px] overflow-visible" : "w-[232px] overflow-hidden"');
    expect(appShellSource).not.toContain("min-[900px]:grid-cols-[184px_minmax(0,1fr)]");
    expect(appShellSource).not.toContain("relative hidden h-dvh min-h-0 overflow-visible");
    expect(appShellSource).toContain("app-sidebar-collapse-rail");
    expect(appShellSource).toContain("app-sidebar-collapse-button");
    expect(appShellSource).toContain("absolute inset-y-0 right-[-10px]");
    expect(appShellSource).toContain("cursor-pointer");
    expect(appShellSource).toContain("app-sidebar-collapse-button pointer-events-none grid h-8 w-8");
    expect(appShellSource).toContain('aria-label={sidebarCollapsed ? tApp("shell.sidebarExpand") : tApp("shell.sidebarCollapse")}');
    expect(appShellSource).toContain("group-hover:opacity-100");
    expect(appShellSource).not.toContain("app-sidebar-collapse-hitbox");
    expect(appShellSource).not.toContain("app-sidebar-resizer");
    expect(appShellSource).not.toContain("MoveHorizontal");
    expect(appShellSource).toContain("group/sidebar-nav-item relative grid min-h-9 w-full min-w-0 overflow-hidden");
    expect(appShellSource).toContain('<span className={cn("min-w-0 truncate", sidebarCollapsed && "sr-only")}>{label}</span>');
    expect(appShellSource).toContain("contentScrollerRef");
    expect(appShellSource).toContain("activeSectionIsCreativeWorkspace");
    expect(appShellSource).toContain("overflow-hidden p-0");
    expect(appShellSource).not.toContain("sticky top-0");
    expect(appShellSource).not.toContain("activeSectionSubtitle");
  });

  it("adds a compact app language switcher to the console sidebar", async () => {
    const source = await readFile(appPath, "utf8");
    const switcherSource = source.slice(source.indexOf("function AppLanguageSwitcher"), source.indexOf("function AccountMenu"));

    expect(source).toContain("Globe2");
    expect(switcherSource).toContain("app-language-switcher");
    expect(switcherSource).toContain("app-language-menu");
    expect(switcherSource).toContain('collapsed ? "mx-auto" : "min-w-0"');
    expect(switcherSource).toContain("grid-cols-[26px_minmax(0,1fr)]");
    expect(switcherSource).toContain('{!collapsed ? <span className="min-w-0 truncate">{getLocaleMeta(currentLocale).label}</span> : null}');
    expect(switcherSource).toContain("bottom-[calc(100%+8px)] left-0 top-auto");
    expect(switcherSource).toContain("supportedLocales.map");
    expect(switcherSource).toContain("getLocaleMeta(locale).label");
    expect(switcherSource).toContain("clientLocaleStorageKey");
    expect(switcherSource).toContain("i18n.changeLanguage(locale)");
    expect(switcherSource).toContain("window.localStorage.setItem");
    expect(switcherSource).toContain("closeOnOutsideClick");
    expect(switcherSource).toContain("closeOnEscape");
    expect(switcherSource).toContain('const languageChangeLabel = i18n.t("common:language.change", { lng: currentLocale });');
    expect(switcherSource).toContain("aria-label={languageChangeLabel}");
    expect(switcherSource).toContain("title={languageChangeLabel}");
    expect(switcherSource).toContain("aria-current={locale === currentLocale ? \"true\" : undefined}");
    expect(source).toContain('{tApp("shell.tagline")}');
    expect(source).toContain("const label = tApp(`navigation.${labelKey}`);");
  });
});
