import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

const appPath = "src/client/App.tsx";
const compactChoiceDropdownPath = "src/client/components/compactChoiceDropdown.tsx";
const zhAppTextPath = "src/i18n/locales/zh/app.json";
const enAppTextPath = "src/i18n/locales/en/app.json";

function sourceBetween(source: string, start: string, end: string): string {
  const startIndex = source.indexOf(start);
  expect(startIndex).toBeGreaterThan(-1);
  const endIndex = source.indexOf(end, startIndex + start.length);
  expect(endIndex).toBeGreaterThan(startIndex);
  return source.slice(startIndex, endIndex);
}

describe("video creation layout source", () => {
  it("uses one product creative workspace for both image and video creation", async () => {
    const source = await readFile(appPath, "utf8");
    const appSource = source.slice(source.indexOf("export function App()"), source.indexOf("function AppLanguageSwitcher"));
    const primaryNavSource = sourceBetween(source, "const primaryNavItems", "const managementNavItems");
    const creativeCase = appSource.slice(appSource.indexOf('case "video"'), appSource.indexOf('case "ledger"'));
    const renderCreativeWorkspaceSource = sourceBetween(appSource, "function renderCreativeWorkspace", "function renderActiveSection");
    const workspaceSource = source.slice(source.indexOf("function ProductCreationWorkspace"), source.indexOf("function ProductCreationProductLibrary"));
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductCreationProductLibrary"));

    expect(primaryNavSource).toContain('labelKey: "creative"');
    expect(primaryNavSource).toContain('id: "video"');
    expect(primaryNavSource).not.toContain('labelKey: "image"');
    expect(creativeCase).toContain('case "video"');
    expect(creativeCase).toContain('case "image"');
    expect(creativeCase).toContain("return renderCreativeWorkspace();");
    expect(renderCreativeWorkspaceSource).toContain("<ProductCreationWorkspace");
    expect(renderCreativeWorkspaceSource).toContain("mode={creativeWorkspaceMode}");
    expect(renderCreativeWorkspaceSource).toContain("onModeChange={(nextMode) => setActiveSection(nextMode)}");
    expect(creativeCase).not.toContain('tApp("image.empty")');
    expect(workspaceSource).toContain("mode: ProductCreativeWorkspaceMode;");
    expect(workspaceSource).toContain("onModeChange: (mode: ProductCreativeWorkspaceMode) => void;");
    expect(composerSource).toContain("buildProductCreativeWorkspace");
    expect(composerSource).not.toContain("ProductCreativeContextBar");
    expect(composerSource).not.toContain("ProductCreativeCommandCenter");
    expect(composerSource).toContain("ProductImageHistoryPanel");
    expect(composerSource).toContain("handleGenerateProductImages");
    expect(composerSource).toContain("onModeChange={onModeChange}");
    expect(composerSource).not.toContain("workspace.modeSwitch");
    expect(composerSource).not.toContain("workspace.modeSummary");
    expect(composerSource).toContain("ProductModeOutputPanel");
    expect(source).toContain('mode === "video"');
    expect(source).toContain("<StoryboardComposerPanel");
    expect(source).not.toContain("<ProductImagePromptPanel");
  });

  it("keeps the main composer free of duplicate product headers and mode tabs", async () => {
    const source = await readFile(appPath, "utf8");
    const workspaceSource = source.slice(source.indexOf("function ProductCreationWorkspace"), source.indexOf("function ProductCreationProductLibrary"));
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductCreationProductLibrary"));

    expect(workspaceSource).toContain("onModeChange: (mode: ProductCreativeWorkspaceMode) => void;");
    expect(composerSource).toContain("ProductCreativeModeSwitch");
    expect(composerSource).not.toContain("<ProductCreativeContextBar");
    expect(composerSource).not.toContain("function ProductCreativeContextBar");
    expect(composerSource).not.toContain("product-creative-context-bar");
    expect(composerSource).not.toContain("workspace.modeSwitch.map");
    expect(composerSource).not.toContain("workspace.modeSummary");
    expect(composerSource).not.toContain("图片工作台");
    expect(composerSource).not.toContain("视频工作台");
  });

  it("keeps internal prompt architecture out of the user-facing creative workspace", async () => {
    const source = await readFile(appPath, "utf8");
    const workbenchSource = sourceBetween(source, "function ProductCreativeWorkbench", "function ProductCreativeSettingsTray");
    const uiWorkspaceSource = sourceBetween(source, "function ProductCreationComposer", "function ProductCreationProductLibrary");
    const workspaceModelSource = await readFile("src/client/productCreativeWorkspace.ts", "utf8");

    expect(workbenchSource).not.toContain("<ProductCreativeContextBar");
    expect(workbenchSource).not.toContain("<ProductCreativeCommandCenter");
    expect(workbenchSource).not.toContain("<ProductCreativeWorkspacePanel");
    expect(workbenchSource).not.toContain("<ProductAssetLedgerPanel");
    expect(workbenchSource).not.toContain("<ProductPromptPipelinePanel");
    expect(source).not.toContain("function ProductCreativeCommandCenter");
    expect(source).not.toContain("product-creative-command-center");
    expect(source).not.toContain("product-creative-compiler-column");
    expect(uiWorkspaceSource).not.toContain("视频提示词编译契约");
    expect(uiWorkspaceSource).not.toContain("图片提示词编译契约");
    expect(uiWorkspaceSource).not.toContain("商品资产账本");
    expect(uiWorkspaceSource).not.toContain("Payload");
    expect(source).not.toContain("function ProductCreativeContextBar");
    expect(source).not.toContain("product-creative-context-bar");
    expect(uiWorkspaceSource).not.toContain("workspace.modeSwitch.map");
    expect(uiWorkspaceSource).not.toContain("workspace.modeSummary");
    expect(uiWorkspaceSource).not.toContain("workspace.memoryChips.map");
    expect(uiWorkspaceSource).not.toContain("workspace.promptPipeline");
    expect(uiWorkspaceSource).not.toContain("workspace.promptCompilerSteps.map");
    expect(uiWorkspaceSource).not.toContain("workspace.assetLedger.map");
    expect(workspaceModelSource).toContain('"visual-asset-pool"');
    expect(workspaceModelSource).toContain('"image-output-records"');
    expect(workspaceModelSource).not.toContain('"reference-images"');
    expect(workspaceModelSource).not.toContain('"image-assets"');
  });

  it("uses a minimal single-composer workspace instead of an architecture dashboard", async () => {
    const source = await readFile(appPath, "utf8");
    const composerSource = sourceBetween(source, "function ProductCreationComposer", "function ProductCreativeWorkbench");
    const workbenchSource = sourceBetween(source, "function ProductCreativeWorkbench", "function ProductCreativeSettingsTray");
    const productDetailsSource = sourceBetween(workbenchSource, "product-creative-product-details", "<ProductComposerReferenceTray");
    const referenceTraySource = sourceBetween(source, "function ProductComposerReferenceTray", "function StoryboardComposerPanel");

    expect(composerSource).toContain("<ProductCreativeWorkbench");
    expect(composerSource).not.toContain("video-generation-controls compact-generation-controls");
    expect(composerSource).not.toContain("min-[1180px]:grid-cols-[250px_minmax(360px,1fr)_350px]");
    expect(composerSource).not.toContain("<ProductModeActionBar");
    expect(composerSource).not.toContain("<ProductModeAssetPanel");
    expect(workbenchSource).toContain("product-creative-workbench");
    expect(workbenchSource).toContain("product-creative-studio");
    expect(workbenchSource).toContain("product-creative-compose-panel");
    expect(workbenchSource).not.toContain("max-w-[960px]");
    expect(workbenchSource).not.toContain("mx-auto");
    expect(workbenchSource).toContain("product-creative-product-details");
    expect(workbenchSource).toContain("product-creative-context-strip");
    expect(workbenchSource).toContain("product-facts-editor");
    expect(workbenchSource).toContain("product-facts-body h-[104px] min-h-[104px] max-h-[104px]");
    expect(workbenchSource).toContain("overflow-y-auto");
    expect(productDetailsSource).toContain("grid-rows-[36px_minmax(104px,auto)]");
    expect(productDetailsSource).toContain("product-facts-header flex h-9 items-center");
    expect(productDetailsSource).toContain("product-facts-action h-9 min-h-9");
    expect(productDetailsSource).toContain("product-creative-product-details grid self-start");
    expect(productDetailsSource).toContain("border-0 bg-transparent px-0 py-0");
    expect(productDetailsSource).not.toContain("border-[var(--border)] bg-[var(--panel)]");
    expect(productDetailsSource).not.toContain('<div className="min-h-5">');
    expect(referenceTraySource).toContain("product-reference-inline grid self-start content-start gap-2 rounded-[8px] px-3 py-2");
    expect(referenceTraySource).toContain('referenceCount > 0 ? "grid-rows-[36px_minmax(104px,auto)]" : "grid-rows-[36px]"');
    expect(referenceTraySource).toContain("product-reference-actions flex h-9 min-w-0 flex-nowrap items-center gap-2");
    expect(referenceTraySource).toContain('tVideo("reference.title")');
    expect(referenceTraySource).toContain("reference-add-button inline-flex h-9 min-h-9");
    expect(referenceTraySource).not.toContain("reference-generate-action");
    expect(referenceTraySource).not.toContain('tVideo("reference.generate")');
    expect(referenceTraySource).not.toContain("onGenerateReferenceImages(product.sku)");
    expect(referenceTraySource).toContain("reference-image-list flex h-[104px] min-h-[104px]");
    expect(productDetailsSource).not.toContain("<details");
    expect(productDetailsSource).not.toContain("<summary");
    expect(productDetailsSource).not.toContain("productDetailsOpen");
    expect(workbenchSource).not.toContain("product-creative-settings");
    expect(workbenchSource).not.toContain("product-creative-media-rail");
    expect(workbenchSource).not.toContain("product-creative-result-rail");
    expect(workbenchSource).not.toContain("min-[1180px]:grid-cols");
    expect(workbenchSource).not.toContain("min-[1760px]:grid-cols");
    expect(workbenchSource).not.toContain("product-creative-column-heading");
    expect(workbenchSource).not.toContain("源数据");
    expect(workbenchSource).not.toContain("创作意图");
    expect(workbenchSource).not.toContain("输出资产");
    expect(workbenchSource).toContain("ProductComposerReferenceTray");
    expect(workbenchSource).toContain("ProductModeOutputPanel");
    expect(workbenchSource).toContain("ProductModeAssetPanel");
    expect(workbenchSource.indexOf("product-creative-product-details")).toBeLessThan(workbenchSource.indexOf("ProductComposerReferenceTray"));
    expect(workbenchSource.indexOf("ProductComposerReferenceTray")).toBeLessThan(workbenchSource.indexOf("ProductModeOutputPanel"));
    expect(workbenchSource).not.toContain("<ProductModeActionBar");
    expect(workbenchSource).toContain("generateVideoButtonLabel={generateVideoButtonLabel}");
    expect(workbenchSource).toContain("generateImageButtonLabel={generateImageButtonLabel}");
    expect(workbenchSource.indexOf("product-creative-compose-panel")).toBeLessThan(workbenchSource.indexOf("ProductModeAssetPanel"));
    expect(workbenchSource.indexOf("ProductModeAssetPanel")).toBeGreaterThan(workbenchSource.indexOf("product-creative-compose-panel"));
  });

  it("keeps mode-specific generation actions in the prompt footer and asset ledgers behind mode components", async () => {
    const source = await readFile(appPath, "utf8");
    const composerBodySource = sourceBetween(source, "function ProductCreationComposer", "function ProductCreativeWorkbench");
    const workbenchSource = sourceBetween(source, "function ProductCreativeWorkbench", "function ProductCreativeSettingsTray");
    const promptPanelSource = sourceBetween(source, "function StoryboardComposerPanel", "function VideoHistoryPanel");
    const assetPanelSource = sourceBetween(source, "function ProductModeAssetPanel", "function ProductModeOutputPanel");

    expect(composerBodySource).toContain("<ProductCreativeWorkbench");
    expect(workbenchSource).not.toContain("<ProductModeActionBar");
    expect(workbenchSource).toContain("<ProductModeAssetPanel");
    expect(composerBodySource).not.toContain("<VideoHistoryPanel");
    expect(composerBodySource).not.toContain("<ProductImageHistoryPanel");

    expect(promptPanelSource).toContain('mode === "video"');
    expect(promptPanelSource).toContain("prompt-composer-primary-action-slot");
    expect(promptPanelSource).toContain("onGenerateVideo");
    expect(promptPanelSource).toContain("onGenerateProductImages");
    expect(promptPanelSource).toContain("primaryActionDisabled");
    expect(promptPanelSource).toContain("primaryActionLabel");
    expect(promptPanelSource).not.toContain("generateVideoSummary");
    expect(promptPanelSource).not.toContain("imageGenerateSummary");
    expect(promptPanelSource).not.toContain("product-creative-action-summary");

    expect(assetPanelSource).toContain('mode === "video"');
    expect(assetPanelSource).toContain("<VideoHistoryPanel");
    expect(assetPanelSource).toContain("<ProductImageHistoryPanel");
    expect(assetPanelSource).not.toContain("<ProductImageAssetPanel");
  });

  it("separates prompt references, text, and action controls so preview text cannot overlap the footer", async () => {
    const source = await readFile(appPath, "utf8");
    const promptPanelSource = sourceBetween(source, "function StoryboardComposerPanel", "function VideoHistoryPanel");

    expect(promptPanelSource).toContain("storyboard-prompt-shell grid min-h-0 grid-rows-[auto_minmax(0,1fr)_auto]");
    expect(promptPanelSource).toContain("rounded-[12px] border border-[var(--border-strong)] bg-[var(--card)]");
    expect(promptPanelSource).toContain("storyboard-prompt-media-row flex min-h-[82px] border-b border-[var(--border)]");
    expect(promptPanelSource).toContain("storyboard-prompt-textarea h-full min-h-[220px] resize-none border-0 bg-transparent");
    expect(promptPanelSource).toContain("prompt-composer-footer grid min-h-12");
    expect(promptPanelSource).not.toContain("Textarea\n          className=\"h-full min-h-[230px] resize-none");
    expect(promptPanelSource).not.toContain("pt-[96px]");
    expect(promptPanelSource).not.toContain("prompt-composer-footer absolute");
    expect(promptPanelSource).not.toContain("image-prompt-media-strip absolute");
  });

  it("routes image creation through a compact product-aware prompt box", async () => {
    const source = await readFile(appPath, "utf8");
    const appSource = sourceBetween(source, "export function App()", "function AppLanguageSwitcher");
    const composerSource = sourceBetween(source, "function ProductCreationComposer", "function ProductCreativeWorkbench");
    const workbenchSource = sourceBetween(source, "function ProductCreativeWorkbench", "function ProductCreativeSettingsTray");
    const settingsTraySource = sourceBetween(source, "function ProductCreativeSettingsTray", "function ProductCreativeToolbarChoice");
    const outputPanelSource = sourceBetween(source, "function ProductModeOutputPanel", "function ProductImageHistoryPanel");
    const promptPanelSource = sourceBetween(source, "function StoryboardComposerPanel", "function VideoHistoryPanel");

    expect(appSource).toContain("async function generateProductReferenceImages(sku: string, options: ProductImageGenerationOptions = {})");
    expect(appSource).toContain("referenceImages: options.referenceImages ?? []");
    expect(appSource).toContain("prompt: options.prompt?.trim() || undefined");
    expect(composerSource).toContain('const [imagePrompt, setImagePrompt] = useState("");');
    expect(composerSource).toContain("setImagePrompt(\"\");");
    expect(composerSource).toContain("const [imagePromptReferences, setImagePromptReferences] = useState<ReferenceImageStatus[]>([]);");
    expect(composerSource).toContain("const [imagePromptReferenceIndex, setImagePromptReferenceIndex] = useState<number | undefined>();");
    expect(composerSource).toContain("const selectedImagePromptReference = imagePromptReferenceIndex === undefined ? undefined : imagePromptReferences[imagePromptReferenceIndex];");
    expect(composerSource).toContain("const selectedImagePromptReferenceNumber = selectedImagePromptReference");
    expect(composerSource).toContain("imagePromptReferences.indexOf(selectedImagePromptReference)");
    expect(composerSource).toContain("const reference = previewableReferenceImages[index];");
    expect(composerSource).toContain("async function handleImagePromptReferenceFiles(files: FileList | File[] | null)");
    expect(composerSource).toContain("const uploadedReferences = uploadedProduct?.reference_image_statuses?.slice(productBeforeUploadCount) ?? [];");
    expect(composerSource).toContain("function acceptedReferenceFiles(files: FileList | File[] | null)");
    expect(composerSource).toContain("setImagePromptReferences((current) => {");
    expect(composerSource).toContain("const nextReferences = [...current];");
    expect(composerSource).toContain("const existingIndex = nextReferences.findIndex((item) => referenceImageKey(item) === referenceImageKey(reference));");
    expect(composerSource).toContain("setImagePromptReferenceIndex(selectedIndex);");
    expect(composerSource).toContain("function handleRemoveImagePromptReference(index: number)");
    expect(composerSource).toContain("setImagePromptReferences((current) => current.filter((_, promptIndex) => promptIndex !== index));");
    expect(composerSource).toContain("setImagePromptReferenceIndex((current) => {");
    expect(composerSource).toContain('const pasteInsidePrompt = event.target instanceof Node');
    expect(composerSource).not.toContain('const pasteInsidePrompt = mode === "image"');
    expect(composerSource).toContain("void handleImagePromptReferenceFiles(files);");
    expect(composerSource).toContain('const generateImageButtonLabel = "生成图片";');
    expect(composerSource).not.toContain("imagePromptReadyLabel");
    expect(composerSource).not.toContain("imageGenerateSummary");
    expect(composerSource).not.toContain("generateVideoSummary");
    expect(composerSource).toContain("await onGenerateReferenceImages(savedProduct.sku, {");
    expect(composerSource).toContain("prompt: imagePrompt,");
    expect(composerSource).toContain("const compiledVideoPrompt = compileProductPrompt({");
    expect(composerSource).toContain("storyboardLines: splitDraftLines(compiledVideoPrompt.prompt)");
    expect(composerSource).toContain("const selectedReferenceImages = selectedCreationReferenceImagesForProduct(savedProduct) ?? [];");
    expect(composerSource).toContain("referenceImages: selectedReferenceImages,");
    expect(composerSource).toContain('onToast(tVideo("storyboard.previewNeedsFacts"))');
    expect(composerSource).toContain('onToast(errorMessage(error))');
    expect(composerSource).toContain("function previewProductForPromptCompiler");
    expect(composerSource).toContain("compileProductPrompt({");
    expect(composerSource).toContain("userPrompt: storyboardDraft,");
    expect(composerSource).toContain("creativeStyle: template");
    expect(composerSource).toContain("const templateOptions = creativeStyleOptions(template, enabledTemplateOptions);");
    expect(promptPanelSource).toContain("<ProductCreativeSettingsTray");
    expect(settingsTraySource).toContain('label={tVideo("controls.creativeStyle")}');
    expect(composerSource).not.toContain("userPrompt: storyboardDraft || template");
    expect(composerSource).not.toContain("const productForPrompt = await onFlushProductFactsAutoSave() ?? selectedProduct;");
    expect(composerSource).not.toContain("const productForStoryboard = await onFlushProductFactsAutoSave() ?? selectedProduct;");
    expect(composerSource).not.toContain("const productForPrompt = await onFlushProductFactsAutoSave() ?? selectedProduct ?? await handleOrganizeProductPackage({ silentSuccess: true })");
    expect(composerSource).toContain("imagePrompt={imagePrompt}");
    expect(composerSource).toContain("onImagePromptChange={setImagePrompt}");
    expect(composerSource).not.toContain("imageTargetLabel={imageTargetLabel}");
    expect(composerSource).toContain("imagePromptReferences={imagePromptReferences}");
    expect(composerSource).toContain("imagePromptReferenceIndex={imagePromptReferenceIndex}");
    expect(composerSource).toContain("selectedImagePromptReference={selectedImagePromptReference}");
    expect(composerSource).toContain("const [previewImagePromptReferenceIndex, setPreviewImagePromptReferenceIndex] = useState<number | undefined>();");
    expect(composerSource).toContain("function handleSelectReferenceImage(index: number)");
    expect(composerSource).toContain("function selectedCreationReferenceImagesForProduct(product: ProductDetail)");
    expect(composerSource).toContain("addImagePromptReferences([reference]);");
    expect(composerSource).not.toContain('if (mode === "image") {\n      addImagePromptReferences([reference]);\n    }');
    expect(composerSource).toContain("function handlePreviewReferenceImage(index: number)");
    expect(composerSource).toContain("setPreviewReferenceImageIndex(index);");
    expect(composerSource).toContain("function handleSelectImagePromptReference(index: number)");
    expect(composerSource).toContain("function handlePreviewImagePromptReference(index: number)");
    expect(composerSource).toContain("setPreviewImagePromptReferenceIndex(index);");
    expect(composerSource).toContain("onImagePromptReferenceSelect={handleSelectImagePromptReference}");
    expect(composerSource).toContain("onImagePromptReferencePreview={handlePreviewImagePromptReference}");
    expect(composerSource).toContain("onImagePromptReferenceRemove={handleRemoveImagePromptReference}");
    expect(composerSource).toContain("onImagePromptReferenceFilesChange={handleImagePromptReferenceFiles}");
    expect(composerSource).toContain("onSelectReferenceImage={handleSelectReferenceImage}");
    expect(composerSource).toContain("onPreviewReferenceImage={handlePreviewReferenceImage}");
    expect(composerSource).toContain("onPendingSelect={handleSelectReferenceImage}");
    expect(composerSource).toContain("onPendingPreview={handlePreviewReferenceImage}");
    expect(composerSource).toContain("images={imagePromptReferences}");
    expect(composerSource).toContain("index={previewImagePromptReferenceIndex}");
    expect(composerSource).not.toContain("imagePromptReferences={previewableReferenceImages}");
    expect(composerSource).toContain("generateImageButtonLabel={generateImageButtonLabel}");
    expect(composerSource).toContain("referenceImages: selectedCreationReferenceImagesForProduct(savedProduct)");
    expect(composerSource).toContain("onModeChange={onModeChange}");
    expect(composerSource).toContain("onImageModelConfigChange={onImageModelConfigChange}");
    expect(workbenchSource).toContain("imagePrompt: string;");
    expect(workbenchSource).toContain("onImagePromptChange: (prompt: string) => void;");
    expect(workbenchSource).not.toContain("imageTargetLabel: string;");
    expect(workbenchSource).toContain("imagePromptReferences: ReferenceImageStatus[];");
    expect(workbenchSource).toContain("imagePromptReferenceIndex?: number;");
    expect(workbenchSource).toContain("selectedImagePromptReference?: ReferenceImageStatus;");
    expect(workbenchSource).toContain("onImagePromptReferenceSelect: (index: number) => void;");
    expect(workbenchSource).toContain("onImagePromptReferencePreview: (index: number) => void;");
    expect(workbenchSource).toContain("onImagePromptReferenceRemove: (index: number) => void;");
    expect(workbenchSource).toContain("onImagePromptReferenceFilesChange: (files: FileList | File[] | null) => void;");
    expect(workbenchSource).toContain("generateImageButtonLabel: string;");
    expect(workbenchSource).toContain("imageModelOptions: ProviderConfigItem[];");
    expect(workbenchSource).toContain("selectedImageModelConfigId: ModelConfigChoice;");
    expect(workbenchSource).toContain("onImageModelConfigChange: (configId: ModelConfigChoice) => void;");
    expect(workbenchSource).toContain("onModeChange: (mode: ProductCreativeWorkspaceMode) => void;");
    expect(outputPanelSource).toContain("imagePrompt={imagePrompt}");
    expect(outputPanelSource).toContain("onImagePromptChange={onImagePromptChange}");
    expect(outputPanelSource).not.toContain("imageTargetLabel={imageTargetLabel}");
    expect(outputPanelSource).toContain("imagePromptReferences={imagePromptReferences}");
    expect(outputPanelSource).toContain("imagePromptReferenceIndex={imagePromptReferenceIndex}");
    expect(outputPanelSource).toContain("selectedImagePromptReference={selectedImagePromptReference}");
    expect(outputPanelSource).toContain("onImagePromptReferenceSelect={onImagePromptReferenceSelect}");
    expect(outputPanelSource).toContain("onImagePromptReferencePreview={onImagePromptReferencePreview}");
    expect(outputPanelSource).toContain("onImagePromptReferenceRemove={onImagePromptReferenceRemove}");
    expect(outputPanelSource).toContain("onImagePromptReferenceFilesChange={onImagePromptReferenceFilesChange}");
    expect(outputPanelSource).toContain("imageModelOptions={imageModelOptions}");
    expect(outputPanelSource).toContain("selectedImageModelConfigId={selectedImageModelConfigId}");
    expect(outputPanelSource).toContain("onImageModelConfigChange={onImageModelConfigChange}");
    expect(outputPanelSource).toContain("onModeChange={onModeChange}");
    expect(outputPanelSource).toContain("<StoryboardComposerPanel");
    expect(outputPanelSource).not.toContain('if (mode === "video")');
    expect(promptPanelSource).toContain('const promptTitle = mode === "image" ? "图片提示词" : tVideo("storyboard.title");');
    expect(promptPanelSource).not.toContain("图片需求");
    expect(promptPanelSource).toContain("storyboard-title-row flex min-h-8 items-center");
    expect(promptPanelSource).toContain("mode: ProductCreativeWorkspaceMode;");
    expect(promptPanelSource).toContain("onModeChange: (mode: ProductCreativeWorkspaceMode) => void;");
    expect(promptPanelSource).toContain("imagePromptReferences: ReferenceImageStatus[];");
    expect(promptPanelSource).toContain("imagePromptReferenceIndex?: number;");
    expect(promptPanelSource).toContain("selectedImagePromptReference?: ReferenceImageStatus;");
    expect(promptPanelSource).toContain("onImagePromptReferenceSelect: (index: number) => void;");
    expect(promptPanelSource).toContain("onImagePromptReferencePreview: (index: number) => void;");
    expect(promptPanelSource).toContain("onImagePromptReferenceRemove: (index: number) => void;");
    expect(promptPanelSource).toContain("onImagePromptReferenceFilesChange: (files: FileList | File[] | null) => void;");
    expect(promptPanelSource).toContain('value={mode === "image" ? imagePrompt : storyboardDraft}');
    expect(promptPanelSource).toContain("onPromptDraftChange(event.target.value)");
    expect(promptPanelSource).toContain("storyboard-prompt-shell grid min-h-0 grid-rows-[auto_minmax(0,1fr)_auto]");
    expect(promptPanelSource).toContain("rounded-[12px] border border-[var(--border-strong)] bg-[var(--card)]");
    expect(promptPanelSource).toContain("storyboard-prompt-media-row flex min-h-[82px] border-b border-[var(--border)]");
    expect(promptPanelSource).toContain("storyboard-prompt-textarea h-full min-h-[220px] resize-none border-0 bg-transparent");
    expect(promptPanelSource).not.toContain("pb-12 pt-[96px]");
    expect(promptPanelSource).not.toContain("product-image-prompt-body");
    expect(promptPanelSource).toContain("image-prompt-media-strip");
    expect(promptPanelSource).toContain("本次参考图");
    expect(promptPanelSource).not.toContain('{mode === "image" ? (');
    expect(promptPanelSource).toContain("image-prompt-add-tile grid h-[70px] w-[184px] shrink-0 cursor-pointer");
    expect(promptPanelSource).toContain("imagePromptReferences.map((image, index) => (");
    expect(promptPanelSource).toContain("<ReferenceImageThumbnail");
    expect(promptPanelSource).toContain('className="image-prompt-reference-item"');
    expect(promptPanelSource).toContain("imagePromptReferenceIndex === index");
    expect(promptPanelSource).toContain("onSelect={() => onImagePromptReferenceSelect(index)}");
    expect(promptPanelSource).toContain("onPreview={() => onImagePromptReferencePreview(index)}");
    expect(promptPanelSource).toContain("onImagePromptReferenceRemove(index)");
    expect(promptPanelSource).toContain("image.original");
    expect(promptPanelSource).toContain("image-prompt-add-tile");
    expect(promptPanelSource).not.toContain("image-prompt-empty-state");
    expect(promptPanelSource).not.toContain("image-prompt-add-hint");
    expect(promptPanelSource).not.toContain("min-w-[190px]");
    expect(promptPanelSource).toContain("添加图片");
    expect(promptPanelSource).toContain("点击 / 拖拽 / 粘贴");
    expect(promptPanelSource).toContain("点上方商品图加入");
    expect(promptPanelSource).not.toContain("可多选 · 拖拽或粘贴图片");
    expect(promptPanelSource).toContain("onImagePromptReferenceFilesChange(event.currentTarget.files)");
    expect(promptPanelSource).not.toContain("image-prompt-target-chip");
    expect(promptPanelSource).not.toContain("清除目标图");
    expect(promptPanelSource).toContain("imagePromptPresets");
    expect(promptPanelSource).toContain("appendImagePromptPreset");
    expect(promptPanelSource).toContain("active-model-control");
    expect(promptPanelSource).toContain("<ProductCreativeModeSwitch");
    expect(promptPanelSource).toContain("onGenerateImagePromptDraft");
    expect(promptPanelSource).toContain('mode === "image" ? onGenerateImagePromptDraft() : onGenerateStoryboardDraft()');
    expect(promptPanelSource).toContain('tVideo("storyboard.generate")');
    expect(promptPanelSource).not.toContain('"预览模型提示词"');
    expect(promptPanelSource).not.toContain("handleOrganizeProductPackage");
    expect(promptPanelSource).not.toContain("storyboard-title-history");
    expect(promptPanelSource).toContain("prompt-composer-primary-action-slot");
    expect(promptPanelSource).toContain("primaryActionIcon");
    expect(promptPanelSource).toContain("primaryActionDisabled");
    expect(promptPanelSource).toContain("primaryActionTitle");
    expect(promptPanelSource).toContain("primaryActionLabel");
    expect(promptPanelSource).toContain("primaryActionEstimate");
    expect(promptPanelSource).not.toContain("primaryActionAmountCny");
    expect(promptPanelSource).toContain('mode === "video" ? onGenerateVideo() : onGenerateProductImages()');
    expect(promptPanelSource).not.toContain("prompt-composer-history-slot");
    expect(promptPanelSource).toContain("<CompactChoiceDropdown");
    expect(promptPanelSource).toContain('mode === "image" ? selectedImageModelConfigId : selectedVideoModelConfigId');
    expect(promptPanelSource).toContain('mode === "image" ? imageModelOptions : videoModelOptions');
    expect(promptPanelSource).toContain('mode === "image" ? onImageModelConfigChange : onVideoModelConfigChange');
    expect(promptPanelSource).toContain("value={activeModelEffectiveConfigId}");
    expect(promptPanelSource).toContain("options={configuredModelOptions(activeModelOptions)}");
    expect(promptPanelSource).toContain("formatOption={(option) => localizedModelConfigChoiceLabel(option, activeModelOptions, tVideo)}");
    expect(promptPanelSource).toContain("onChange={activeModelConfigChange}");
    expect(promptPanelSource).not.toContain("<Badge className=\"max-w-[180px] truncate\">{imageModelLabel}</Badge>");
    expect(promptPanelSource).toContain("generateImageButtonLabel: string;");
    expect(promptPanelSource).toContain("mode === \"video\" ? generateVideoButtonLabel : generateImageButtonLabel");
    expect(promptPanelSource).toContain("title={primaryActionTitle}");
  });

  it("fits mode asset history inside the output column instead of reusing a full-width page section", async () => {
    const source = await readFile(appPath, "utf8");
    const workbenchSource = sourceBetween(source, "function ProductCreativeWorkbench", "function ProductCreativeSettingsTray");
    const assetPanelSource = sourceBetween(source, "function ProductModeAssetPanel", "function ProductModeOutputPanel");
    const imageHistorySource = sourceBetween(source, "function ProductImageHistoryPanel", "function ProductCreationProductLibrary");
    const videoHistorySource = sourceBetween(source, "function VideoHistoryPanel", "function ProductLibraryHome");

    expect(workbenchSource).toContain('surface="workbench"');
    expect(assetPanelSource).toContain('surface?: ProductCreativeAssetPanelSurface;');
    expect(assetPanelSource).toContain('surface={surface}');
    expect(imageHistorySource).toContain("ProductCreativeAssetPanelSurface");
    expect(videoHistorySource).toContain("ProductCreativeAssetPanelSurface");
    expect(imageHistorySource).toContain("product-creative-asset-panel");
    expect(videoHistorySource).toContain("product-creative-asset-panel");
    expect(imageHistorySource).not.toContain('className="grid gap-3 border-t border-[var(--border)] bg-[var(--card)] p-5"');
    expect(videoHistorySource).not.toContain('className="grid gap-3 border-t border-[var(--border)] bg-[var(--card)] p-5"');
  });

  it("does not double count reference images as image output assets in the creative workspace", async () => {
    const source = await readFile(appPath, "utf8");
    const composerSource = sourceBetween(source, "function ProductCreationComposer", "function ProductCreativeWorkbench");
    const historyShellSource = sourceBetween(source, '<details className="product-creative-history', "</details>");
    const assetPanelSource = sourceBetween(source, "function ProductModeAssetPanel", "function ProductModeOutputPanel");
    const imageHistorySource = sourceBetween(source, "function ProductImageHistoryPanel", "function ProductCreationProductLibrary");

    expect(composerSource).toContain("const productImageAssetCount = 0");
    expect(composerSource).toContain("imageAssetCount: productImageAssetCount");
    expect(composerSource).not.toContain("imageAssetCount: previewableReferenceImages.length");
    expect(historyShellSource).toContain('<span>{tVideo("history.title")}</span>');
    expect(historyShellSource).toContain("workspace.assetSummary.imageAssets");
    expect(historyShellSource).not.toContain("商品图片");
    expect(historyShellSource).not.toContain("previewableReferenceImages.length");
    expect(assetPanelSource).toContain("<ProductImageHistoryPanel");
    expect(assetPanelSource).not.toContain("<ProductImageAssetPanel");
    expect(imageHistorySource).toContain("暂无图片生成记录");
    expect(imageHistorySource).not.toContain("保存在当前商品下，图片优化和视频生成都会复用这些参考图");
    expect(imageHistorySource).not.toContain("商品图片资产");
    expect(imageHistorySource).not.toContain("图片模块产物会继续沉淀到同一个商品，供视频模块复用");
  });

  it("renders video creation as product library plus operation workspace instead of a top control bar", async () => {
    const source = await readFile(appPath, "utf8");
    const dropdownSource = await readFile("src/client/components/compactChoiceDropdown.tsx", "utf8");
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductComposerReferenceTray"));
    const storyboardPanelSource = source.slice(source.indexOf("function StoryboardComposerPanel"), source.indexOf("function VideoHistoryPanel"));

    expect(composerSource).toContain("video-workspace-shell");
    expect(composerSource).toContain("h-[100dvh] max-h-[100dvh] min-h-0 grid-rows-[minmax(0,1fr)]");
    expect(composerSource).toContain("transition-[grid-template-columns] duration-200");
    expect(composerSource).toContain("min-[900px]:grid-cols-[var(--product-library-column-width)_minmax(0,1fr)]");
    expect(composerSource).toContain('style={{ "--product-library-column-width": `${productLibraryColumnWidth}px` } as CSSProperties}');
    expect(composerSource).toContain("PRODUCT_LIBRARY_DEFAULT_WIDTH");
    expect(composerSource).toContain("PRODUCT_LIBRARY_COLLAPSED_WIDTH");
    expect(composerSource).not.toContain("PRODUCT_LIBRARY_COLLAPSE_SNAP_WIDTH");
    expect(composerSource).not.toContain("PRODUCT_LIBRARY_MIN_WIDTH");
    expect(composerSource).not.toContain("PRODUCT_LIBRARY_MAX_WIDTH");
    expect(composerSource).not.toContain("min-[900px]:grid-cols-[292px_minmax(0,1fr)]");
    expect(composerSource).toContain("productLibraryCollapsed");
    expect(composerSource).toContain("productLibraryColumnWidth");
    expect(composerSource).not.toContain("const [productLibraryWidth");
    expect(composerSource).not.toContain("handleProductLibraryResizeStart");
    expect(composerSource).not.toContain("handleProductLibraryResizeKeyDown");
    expect(composerSource).not.toContain('role="separator"');
    expect(composerSource).not.toContain('aria-orientation="vertical"');
    expect(composerSource).not.toContain("aria-valuenow={productLibraryColumnWidth}");
    expect(composerSource).toContain("video-product-library-collapse-rail");
    expect(composerSource).toContain("video-product-library-collapse-button");
    expect(composerSource).toContain("transition-[left,color]");
    expect(composerSource).not.toContain("video-product-library-resizer");
    expect(composerSource).not.toContain("productLibraryResizing");
    expect(composerSource).not.toContain("setProductLibraryResizing");
    expect(composerSource).not.toContain("MoveHorizontal");
    expect(composerSource).toContain("cursor-pointer");
    expect(composerSource).toContain("opacity-0");
    expect(composerSource).toContain("group-hover:opacity-100");
    expect(composerSource).toContain('aria-label={productLibraryCollapsed ? tVideo("productLibrary.expand") : tVideo("productLibrary.collapse")}');
    expect(composerSource).toContain('title={productLibraryCollapsed ? tVideo("productLibrary.expand") : tVideo("productLibrary.collapse")}');
    expect(composerSource).toContain("onClick={() => setProductLibraryCollapsed((collapsed) => !collapsed)}");
    expect(composerSource).not.toContain("拖动调整商品库宽度");
    expect(composerSource).toContain("video-product-library-column");
    expect(composerSource).toContain("video-operation-column");
    expect(composerSource).toContain("grid content-start gap-3");
    expect(composerSource).not.toContain("grid min-h-full content-start gap-3");
    expect(composerSource).toContain("ProductCreativeWorkbench");
    expect(composerSource).toContain("product-creative-workbench");
    expect(composerSource).toContain("product-creative-studio");
    expect(composerSource).toContain("product-creative-controls");
    expect(composerSource).toContain("prompt-inline-settings");
    expect(composerSource).toContain("flex-nowrap");
    expect(composerSource).toContain("overflow-visible");
    expect(composerSource).toContain('menuPlacement="top"');
    expect(composerSource).toContain('menuWidth="content"');
    expect(composerSource).not.toContain("prompt-inline-settings flex min-w-0 flex-1 flex-nowrap items-center gap-1 overflow-x-auto");
    expect(dropdownSource).toContain('menuWidth?: "trigger" | "content";');
    expect(dropdownSource).toContain("formatActiveLabel?: (option: T) => string;");
    expect(dropdownSource).toContain("formatActiveLabel?.(value) ?? formatOption(value)");
    expect(dropdownSource).toContain('menuWidth === "content"');
    expect(dropdownSource).toContain("w-max");
    expect(dropdownSource).toContain("max-w-[min(280px,calc(100vw-48px))]");
    expect(dropdownSource).toContain("hidePillLabel?: boolean;");
    expect(dropdownSource).toContain("pill && micro &&");
    expect(dropdownSource).toContain("gap-0.5");
    expect(dropdownSource).toContain("grid-cols-[14px_minmax(0,1fr)]");
    expect(dropdownSource).toContain("CheckCircle2 size={11}");
    expect(dropdownSource).not.toContain('<span className="min-w-0 truncate">{formatOption(option)}</span>');
    expect(source).toContain("active-model-control");
    expect(composerSource).toContain('layout="pill"');
    expect(composerSource).toContain("ProductCreativeToolbarChoice");
    expect(composerSource).not.toContain("model-scheme-chip-row");
    expect(composerSource).not.toContain("ModelSchemeChip");
    expect(composerSource).not.toContain("{schemeSummary}");
    expect(composerSource).toContain('label={tVideo("controls.resolution")}');
    expect(composerSource).toContain("videoResolutionOptions");
    expect(composerSource).toContain("videoResolutionLabel");
    expect(composerSource).toContain("selectedVideoResolution");
    expect(composerSource).toContain("onVideoResolutionChange");
    expect(composerSource).toContain('label={tVideo("controls.aspectRatio")}');
    expect(composerSource).toContain("videoAspectRatioOptions");
    expect(composerSource).toContain("videoAspectRatioLabel");
    expect(composerSource).toContain("selectedVideoAspectRatio");
    expect(composerSource).toContain("onVideoAspectRatioChange");
    expect(composerSource).toContain('const languageOptions: FinalVideoLanguage[] = ["ja", "zh", "en"]');
    expect(source).toContain("compactFinalLanguageLabel(option, tVideo)");
    expect(composerSource).toContain('density="micro"');
    expect(storyboardPanelSource).toContain("prompt-composer-primary-action-slot");
    expect(storyboardPanelSource).toContain("primaryActionLabel");
    expect(composerSource).not.toContain("video-generate-summary");
    expect(composerSource).not.toContain("{generateVideoSummary}");
    expect(composerSource).not.toContain("product-creative-action-summary");
    expect(composerSource).not.toContain("video-generate-summary min-w-0 truncate");
    expect(composerSource).not.toContain("generateVideoSummaryItems.map");
    expect(composerSource).not.toContain("video-generate-summary-item");
    expect(composerSource).not.toContain("video-generate-summary-separator");
    expect(composerSource).not.toContain("generation-status-message");
    expect(composerSource).not.toContain("video-generate-status-center");
    expect(composerSource).not.toContain("subtitle={generateVideoSummary}");
    expect(composerSource).not.toContain("model-scheme-summary min-w-0 whitespace-normal break-words");
    expect(composerSource).not.toContain("model-scheme-summary min-w-0 truncate");
    expect(composerSource).not.toContain("<div className=\"min-w-0 truncate text-xs font-bold text-[var(--muted)]\">{schemeSummary}</div>");
    expect(composerSource).toContain("resolution: selectedVideoResolution");
    expect(composerSource).toContain("aspectRatio: selectedVideoAspectRatio");
    expect(composerSource).toContain("ProductCreationProductLibrary");
    expect(composerSource).toContain("ProductCreationOperationWorkspace");
    expect(composerSource).toContain("collapsed={productLibraryCollapsed}");
    expect(composerSource).toContain("productLibrarySearchQuery");
    expect(composerSource).toContain("filterProductLibraryProducts(productOptions, productLibrarySearchQuery");
    expect(composerSource).toContain("product-library-search");
    expect(composerSource).toContain('aria-label={tVideo("productLibrary.search")}');
    expect(composerSource).toContain('placeholder={tVideo("productLibrary.search")}');
    expect(composerSource).not.toContain("搜索商品 / SKU");
    expect(composerSource).toContain("product-library-scroll min-h-0 overflow-y-auto");
    expect(composerSource).toContain('{tVideo("productLibrary.noMatches")}');
    expect(composerSource).toContain('{tVideo("productLibrary.clearSearch")}');
    expect(composerSource).not.toContain("手动填写或粘贴商品资料");
    expect(composerSource).not.toContain("footer={");
    expect(composerSource).not.toContain("product-control-bar");
    expect(composerSource).not.toContain("video-parameter-row grid");
    expect(composerSource).not.toContain("<ProductCreationProductPicker");

    const promptPanelIndex = source.indexOf("<ProductModeOutputPanel");
    const assetPanelIndex = source.indexOf("<ProductModeAssetPanel");
    expect(promptPanelIndex).toBeGreaterThan(-1);
    expect(assetPanelIndex).toBeGreaterThan(-1);
    expect(promptPanelIndex).toBeLessThan(assetPanelIndex);
  });

  it("localizes video workspace UI without translating product data fields", async () => {
    const source = await readFile(appPath, "utf8");
    const appSource = source.slice(source.indexOf("export function App()"), source.indexOf("function AppLanguageSwitcher"));
    const workspaceSource = source.slice(source.indexOf("function ProductCreationWorkspace"), source.indexOf("function ProductLibraryHome"));
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductCreationProductLibrary"));
    const librarySource = source.slice(source.indexOf("function ProductCreationProductLibrary"), source.indexOf("function ProductCreationOperationWorkspace"));
    const operationSource = source.slice(source.indexOf("function ProductCreationOperationWorkspace"), source.indexOf("function ProductComposerReferenceTray"));
    const referenceTraySource = source.slice(source.indexOf("function ProductComposerReferenceTray"), source.indexOf("function StoryboardComposerPanel"));
    const storyboardPanelSource = source.slice(source.indexOf("function StoryboardComposerPanel"), source.indexOf("function VideoHistoryPanel"));
    const historyPanelSource = source.slice(source.indexOf("function VideoHistoryPanel"), source.indexOf("function ProductLibraryHome"));
    const referenceThumbnailSource = sourceBetween(source, "function ReferenceImageThumbnail", "function ReferenceImageFigure");
    const referenceFigureSource = source.slice(source.indexOf("function ReferenceImageFigure"), source.indexOf("function ReferenceImagePreviewDialog"));
    const referencePreviewSource = source.slice(source.indexOf("function ReferenceImagePreviewDialog"), source.indexOf("function ProductEntryModeButton"));
    const helperSource = source.slice(source.indexOf("function localizedVideoLabel"), source.indexOf("function jobStatusTone"));

    expect(appSource).toContain('const [studioStoryboardDraft, setStudioStoryboardDraft] = useState("");');
    expect(appSource).not.toContain("injectTemplateStoryboardDraft(nextTemplate);");
    expect(appSource).not.toContain("function injectTemplateStoryboardDraft(nextTemplate: TemplateName)");
    expect(appSource).not.toContain("setStudioStoryboardDraft(localizedDefaultStoryboardDraft(nextTemplate, duration, appLocale))");
    expect(appSource).not.toContain("localizedDefaultStoryboardDraft(defaultVideoTemplate, defaultVideoDurationSeconds, appLocale)");
    expect(appSource).not.toContain("if (storyboardDraftTouched) return;");
    expect(appSource).not.toContain("[template, duration, appLocale, storyboardDraftTouched]");
    expect(workspaceSource).toContain("appLocale={appLocale}");
    expect(composerSource).toContain('const tVideo = (key: string, options?: Record<string, unknown>) => i18n.t(`app:videoStudio.${key}`, { lng: appLocale, ...options });');
    expect(composerSource).toContain('title={draft.title_ja.trim() || selectedProduct?.title_ja || tVideo("newProduct.title")}');
    expect(composerSource).toContain('value={importText}');
    expect(composerSource).toContain('storyboardDraft={storyboardDraft}');
    expect(composerSource).toContain('draftTitle={draft.title_ja}');
    expect(composerSource).toContain('onToast(tVideo("generate.packageReadyToast"), "ok")');
    expect(composerSource).toContain('onToast(tVideo("generate.queuedToast"), "ok")');
    expect(composerSource).toContain('onToast(tVideo("generate.imageOnlyToast"))');
    expect(storyboardPanelSource).toContain("primaryActionLabel");
    expect(librarySource).toContain("product.title_ja");
    expect(librarySource).toContain('const title = active && draftProductTitle ? draftProductTitle : product.title_ja;');
    expect(librarySource).toContain('title={title}');
    expect(librarySource).toContain('aria-label={`${tVideo("productLibrary.deleteProduct")} ${product.title_ja}`}');
    expect(librarySource).toContain('const tProductStatus = makeAppTranslator("productStatus")');
    expect(librarySource).toContain('const status = productLibraryStatus(product, tProductStatus)');
    expect(operationSource).toContain('{badge ? <Badge className="shrink-0" tone="neutral">{badge}</Badge> : null}');
    expect(referenceTraySource).toContain('tVideo("reference.add")');
    expect(referenceTraySource).toContain('tVideo("reference.title")');
    expect(referenceTraySource).not.toContain('tVideo("reference.generate")');
    expect(referenceTraySource).toContain('image.original');
    expect(referenceTraySource).toContain('fileName');
    expect(referenceThumbnailSource).toContain("image-reference-thumbnail");
    expect(referenceThumbnailSource).toContain("image-prompt-reference-thumb");
    expect(referenceThumbnailSource).toContain("singleClickTimerRef");
    expect(referenceThumbnailSource).toContain("onClick={handleClick}");
    expect(referenceThumbnailSource).toContain("onDoubleClick={handleDoubleClick}");
    expect(referenceThumbnailSource).toContain("window.setTimeout(onSelect");
    expect(referenceThumbnailSource).toContain("window.clearTimeout(singleClickTimerRef.current)");
    expect(referenceThumbnailSource).toContain("image-prompt-reference-remove");
    expect(referenceThumbnailSource).toContain("function ReferenceImageRemoveButton");
    expect(referenceThumbnailSource).toContain("right-1 top-1 grid h-5 w-5");
    expect(referenceThumbnailSource).toContain("<X size={11} strokeWidth={2.4} />");
    expect(referenceFigureSource).toContain('tVideo("reference.item", { index: index + 1 })');
    expect(referenceFigureSource).toContain('image.original');
    expect(referenceFigureSource).toContain("grid-cols-[64px_minmax(0,1fr)_28px]");
    expect(referenceFigureSource).toContain("<ReferenceImageThumbnail");
    expect(referenceFigureSource).toContain("onSelect={onSelect}");
    expect(referenceFigureSource).toContain("onPreview={onPreview}");
    expect(referenceFigureSource).toContain("<ReferenceImageRemoveButton");
    expect(referenceFigureSource).toContain("className=\"right-2 top-1/2 -translate-y-1/2\"");
    expect(referenceFigureSource).not.toContain("reference-image-actions");
    expect(referenceFigureSource).not.toContain('title={tVideo("reference.selectPromptTarget")}');
    expect(referencePreviewSource).toContain('aria-label={tVideo("reference.previewDialogTitle")}');
    expect(referencePreviewSource).toContain('{image.original}');
    expect(storyboardPanelSource).toContain('tVideo("storyboard.title")');
    expect(storyboardPanelSource).toContain('tVideo("storyboard.placeholder")');
    expect(storyboardPanelSource).not.toContain("<Badge>{localizedTemplateLabel(template, tVideo)}</Badge>");
    expect(storyboardPanelSource).not.toContain("<Badge>{formatDuration(duration)}</Badge>");
    expect(storyboardPanelSource).not.toContain("historyPreview(record.script, appLocale)");
    expect(historyPanelSource).toContain('tVideo("history.title")');
    expect(historyPanelSource).toContain("<VideoHashtagChips tVideo={tVideo}");
    expect(historyPanelSource).toContain("videoDownloadProductContext(product, draft, importText)");
    expect(helperSource).toContain('return tVideo("labels.video", { index: index + 1 });');
    expect(helperSource).toContain('onToast(tVideo("history.tagsCopiedToast"), "ok")');
    expect(helperSource).not.toContain('function localizedDefaultStoryboardDraft(template: TemplateName');
    expect(helperSource).not.toContain('i18n.t(`app:videoStudio.storyboard.defaultDrafts.${templateKey}`');
    expect(helperSource).not.toContain('function storyboardTemplateResourceKey(template: TemplateName): string');

    expect(composerSource).not.toContain('label="模型方案"');
    expect(composerSource).not.toContain('label="视频风格"');
    expect(composerSource).not.toContain('label="视频时长"');
    expect(composerSource).not.toContain('label="成片语言"');
    expect(composerSource).not.toContain('label="生成视频"');
    expect(referenceTraySource).not.toContain(">参考图<");
    expect(referenceFigureSource).not.toContain(">参考图 {index + 1}<");
    expect(referencePreviewSource).not.toContain('aria-label="参考图预览"');
    expect(storyboardPanelSource).not.toContain(">脚本分镜<");
    expect(historyPanelSource).not.toContain(">历史记录<");
  });

  it("keeps active model selection behind one compact capability control", async () => {
    const source = await readFile(appPath, "utf8");
    const compactChoiceSource = await readFile(compactChoiceDropdownPath, "utf8");
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductComposerReferenceTray"));
    const referenceTraySource = source.slice(source.indexOf("function ProductComposerReferenceTray"), source.indexOf("function StoryboardComposerPanel"));
    const storyboardPanelSource = source.slice(source.indexOf("function StoryboardComposerPanel"), source.indexOf("function VideoHistoryPanel"));
    const settingsTraySource = sourceBetween(source, "function ProductCreativeSettingsTray", "function ProductCreativeToolbarChoice");
    const modeSwitchSource = sourceBetween(source, "function ProductCreativeModeSwitch", "function ProductCreativeToolbarChoice");

    expect(composerSource).not.toContain("localizedModelSchemeSummary");
    expect(composerSource).not.toContain("schemeSummary");
    expect(storyboardPanelSource).toContain("prompt-composer-footer");
    expect(storyboardPanelSource).toContain("<ProductCreativeModeSwitch");
    expect(storyboardPanelSource).toContain("<ProductCreativeSettingsTray");
    expect(storyboardPanelSource).toContain("prompt-composer-footer grid min-h-12");
    expect(storyboardPanelSource).toContain("grid-cols-[auto_minmax(0,1fr)_minmax(176px,240px)]");
    expect(storyboardPanelSource).toContain("h-10 min-h-10");
    expect(storyboardPanelSource).toContain("prompt-composer-mode-slot");
    expect(storyboardPanelSource).toContain("prompt-composer-settings-slot");
    expect(storyboardPanelSource).toContain("prompt-composer-primary-action-slot");
    expect(storyboardPanelSource).not.toContain("storyboard-title-history");
    expect(modeSwitchSource).toContain("product-creative-mode-switch flex h-10 shrink-0 items-center gap-1.5");
    expect(storyboardPanelSource).toContain("prompt-composer-settings-slot flex min-w-0 flex-nowrap items-center gap-1.5 overflow-visible");
    expect(storyboardPanelSource).toContain("min-w-[176px] max-w-[240px]");
    expect(storyboardPanelSource).not.toContain('Badge className="min-h-5 shrink-0 px-1.5 text-[10px]"');
    expect(storyboardPanelSource).toContain("whitespace-nowrap");
    expect(storyboardPanelSource).toContain("active-model-control w-auto min-w-0 max-w-none");
    expect(storyboardPanelSource).not.toContain("active-model-control min-w-[196px] max-w-[260px]");
    expect(compactChoiceSource).toContain('pill && "min-h-9 w-auto');
    expect(compactChoiceSource).not.toContain('pill && "min-h-9 w-full');
    expect(storyboardPanelSource).toContain('mode === "image" ? selectedImageModelConfigId : selectedVideoModelConfigId');
    expect(storyboardPanelSource).toContain('mode === "image" ? imageModelOptions : videoModelOptions');
    expect(storyboardPanelSource).toContain('mode === "image" ? onImageModelConfigChange : onVideoModelConfigChange');
    expect(storyboardPanelSource).toContain("activeModelLabel");
    expect(storyboardPanelSource).toContain("activeModelEffectiveConfigId");
    expect(storyboardPanelSource).toContain("activeModelIcon");
    expect(storyboardPanelSource).toContain("options={configuredModelOptions(activeModelOptions)}");
    expect(settingsTraySource).toContain("prompt-inline-settings");
    expect(settingsTraySource).toContain("gap-0.5");
    expect(settingsTraySource).not.toContain("model-scheme-control");
    expect(settingsTraySource).not.toContain("hidePillLabel");
    expect(settingsTraySource).not.toContain("localizedModelSchemeChoiceLabel");
    expect(settingsTraySource).toContain("formatActiveLabel={(option) => localizedTemplateLabel(option, tVideo)}");
    expect(settingsTraySource).toContain("formatActiveLabel={(option) => compactFinalLanguageLabel(option, tVideo)}");
    expect(settingsTraySource).toContain('`${option} 个`');
    expect(settingsTraySource).toContain("overflow-visible");
    expect(storyboardPanelSource).toContain('menuPlacement="top"');
    expect(storyboardPanelSource).toContain('menuWidth="content"');
    expect(storyboardPanelSource.indexOf("prompt-composer-footer")).toBeLessThan(storyboardPanelSource.indexOf("<ProductCreativeModeSwitch"));
    expect(storyboardPanelSource.indexOf("<ProductCreativeModeSwitch")).toBeLessThan(storyboardPanelSource.indexOf("active-model-control"));
    expect(storyboardPanelSource.indexOf("active-model-control")).toBeLessThan(storyboardPanelSource.indexOf("<ProductCreativeSettingsTray"));
    expect(storyboardPanelSource.indexOf("prompt-composer-mode-slot")).toBeLessThan(storyboardPanelSource.indexOf("prompt-composer-settings-slot"));
    expect(storyboardPanelSource.indexOf("prompt-composer-settings-slot")).toBeLessThan(storyboardPanelSource.indexOf("prompt-composer-primary-action-slot"));
    expect(storyboardPanelSource).not.toContain("storyboard-title-history");
    expect(composerSource).not.toContain("model-scheme-chip-row");
    expect(composerSource).not.toContain('{ label: tVideo("modelChips.text"), value: localizedModelConfigChoiceLabel(selectedTextModelConfigId, textModelOptions, tVideo) }');
    expect(composerSource).not.toContain('{ label: tVideo("modelChips.image"), value: localizedModelConfigChoiceLabel(selectedImageModelConfigId, imageModelOptions, tVideo) }');
    expect(composerSource).not.toContain('{ label: tVideo("modelChips.video"), value: localizedModelConfigChoiceLabel(selectedVideoModelConfigId, videoModelOptions, tVideo) }');
    expect(composerSource).not.toContain('{ label: "文", value: modelConfigChoiceLabel');
    expect(composerSource).not.toContain('{ label: "图", value: modelConfigChoiceLabel');
    expect(composerSource).not.toContain('{ label: "视", value: modelConfigChoiceLabel');
    expect(composerSource).not.toContain("textModelLabel={modelConfigChoiceLabel");
    expect(referenceTraySource).not.toContain("图片模型");
    expect(referenceTraySource).not.toContain("modelConfigChoiceLabel(selectedImageModelConfigId");
    expect(referenceTraySource).not.toContain("selectedImageModelConfigId");
    expect(referenceTraySource).not.toContain("imageModelOptions");
    expect(storyboardPanelSource).not.toContain("文本模型:");
    expect(storyboardPanelSource).not.toContain("textModelLabel");
  });

  it("surfaces concise per-action estimates inside stable video creation action buttons", async () => {
    const source = await readFile(appPath, "utf8");
    const zhAppText = await readFile(zhAppTextPath, "utf8");
    const enAppText = await readFile(enAppTextPath, "utf8");
    const appSource = source.slice(source.indexOf("export function App()"), source.indexOf("function AppLanguageSwitcher"));
    const workspaceSource = source.slice(source.indexOf("function ProductCreationWorkspace"), source.indexOf("function ProductLibraryHome"));
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductCreationProductLibrary"));
    const referenceTraySource = source.slice(source.indexOf("function ProductComposerReferenceTray"), source.indexOf("function StoryboardComposerPanel"));
    const storyboardPanelSource = source.slice(source.indexOf("function StoryboardComposerPanel"), source.indexOf("function VideoHistoryPanel"));
    const productDetailsSource = sourceBetween(source, "product-creative-product-details", "<ProductComposerReferenceTray");
    const storyboardFooterSource = storyboardPanelSource.slice(storyboardPanelSource.indexOf("prompt-composer-footer"));
    const actionButtonCostSource = source.slice(source.indexOf("function ActionButtonCost"), source.indexOf("function versionLabel"));

    expect(appSource).toContain('postJson<BillingEstimatesResponse>("/api/billing-estimates"');
    expect(appSource).toContain("videoResolution: selectedVideoResolution");
    expect(appSource).toContain("videoAspectRatio: selectedVideoAspectRatio");
    expect(workspaceSource).toContain("billingEstimates={billingEstimates}");
    expect(composerSource).toContain("billingEstimates?: BillingEstimatesResponse");
    expect(composerSource).toContain('organizeProductEstimate={billingEstimates?.estimates.organizeProduct}');
    expect(composerSource).not.toContain('referenceImagesEstimate={billingEstimates?.estimates.referenceImages}');
    expect(composerSource).not.toContain('storyboardEstimate={billingEstimates?.estimates.storyboard}');
    expect(composerSource).not.toContain("estimate={storyboardEstimate}");
    expect(composerSource).toContain('videoEstimate={billingEstimates?.estimates.video}');
    expect(composerSource).toContain('imageEstimate={billingEstimates?.estimates.referenceImages}');
    expect(referenceTraySource).not.toContain("estimate?: BillingActionEstimate");
    expect(referenceTraySource).not.toContain('<ActionButtonCost tVideo={tVideo} estimate={estimate} />');
    expect(storyboardPanelSource).not.toContain("estimate?: BillingActionEstimate");
    expect(storyboardPanelSource).not.toContain('<ActionButtonCost tVideo={tVideo} estimate={estimate} />');
    expect(productDetailsSource).toContain("product-facts-header");
    expect(productDetailsSource).toContain("product-facts-action");
    expect(productDetailsSource.indexOf("product-facts-action")).toBeLessThan(productDetailsSource.indexOf("product-facts-editor"));
    expect(productDetailsSource).not.toContain("sm:grid-cols-[minmax(0,1fr)_auto]");
    expect(storyboardPanelSource).toContain("storyboard-title-row");
    expect(storyboardPanelSource).toContain("storyboard-title-action");
    expect(storyboardPanelSource).not.toContain("storyboard-title-history");
    expect(storyboardPanelSource).toContain("promptPreviewActionLabel");
    expect(storyboardPanelSource).toContain("promptPreviewActionDisabled");
    expect(storyboardPanelSource).toContain('variant="ghost"');
    expect(storyboardPanelSource).toContain("max-w-[112px]");
    expect(storyboardPanelSource).not.toContain("w-[168px]");
    expect(storyboardPanelSource).not.toContain('"预览模型提示词"');
    expect(storyboardPanelSource).not.toContain("storyboard-title-history");
    expect(storyboardPanelSource.indexOf("storyboard-title-action")).toBeLessThan(storyboardPanelSource.indexOf("storyboard-history-dropdown"));
    expect(storyboardFooterSource).toContain("prompt-composer-primary-action-slot");
    expect(storyboardFooterSource).toContain("primaryActionEstimate");
    expect(storyboardFooterSource).toContain("primaryActionLabel");
    expect(storyboardFooterSource).not.toContain("primaryActionAmountCny");
    expect(storyboardFooterSource).toContain("<ActionButtonCost tVideo={tVideo} estimate={primaryActionEstimate} />");
    expect(source).toContain("function ActionButtonCost");
    expect(source).not.toContain("const primaryActionAmountCny = mode === \"video\" ? videoEstimate?.upstreamEstimatedCostCny : undefined;");
    expect(actionButtonCostSource).toContain('tVideo("costHints.estimated", {');
    expect(actionButtonCostSource).toContain("estimate.walletEstimatedChargeCny");
    expect(actionButtonCostSource).not.toContain("amountCny?: number");
    expect(actionButtonCostSource).not.toContain('kind === "video"');
    expect(source).not.toContain("costHints.videoEstimated");
    expect(source).not.toContain("costHints.videoDetail");
    expect(source).not.toContain("本次视频预估");
    expect(source).not.toContain("function ActionCostHint");
    expect(source).not.toContain('tVideo("costHints.estimatedCharge"');
    expect(zhAppText).toContain('"expectedCost": "预计扣余额"');
    expect(zhAppText).toContain('"estimated": "预估扣费 ¥{{amount}}"');
    expect(enAppText).toContain('"expectedCost": "Est. Wallet Charge"');
    expect(enAppText).toContain('"estimated": "Est. charge ¥{{amount}}"');
    expect(source).not.toContain("生成预检");
  });

  it("moves account controls into the left navigation shell and keeps video content full bleed", async () => {
    const source = await readFile(appPath, "utf8");
    const appShellSource = source.slice(source.indexOf("<main"), source.indexOf("function AccountMenu"));
    const brandSource = appShellSource.slice(appShellSource.indexOf("<BrandLogo"), appShellSource.indexOf("<nav"));
    const accountDockSource = appShellSource.slice(appShellSource.indexOf("app-sidebar-account"), appShellSource.indexOf("</aside>"));

    expect(appShellSource).toContain("app-sidebar-account");
    expect(appShellSource).toContain("<AppLanguageSwitcher");
    expect(appShellSource).toContain("collapsed={sidebarCollapsed}");
    expect(brandSource).not.toContain("<AppLanguageSwitcher");
    expect(accountDockSource).toContain("<AccountMenu");
    expect(accountDockSource).toContain("<AppLanguageSwitcher");
    expect(accountDockSource.indexOf("<AccountMenu")).toBeLessThan(accountDockSource.indexOf("<AppLanguageSwitcher"));
    expect(accountDockSource).toContain("{authSession.authEnabled ? (");
    expect(accountDockSource).toContain(") : null}");
    expect(accountDockSource).toContain('sidebarCollapsed ? "grid gap-1.5 px-1.5" : "grid gap-1.5 px-2.5"');
    expect(accountDockSource).not.toContain("grid-cols-[minmax(0,1fr)_36px]");
    expect(appShellSource).toContain("relative flex h-[72px] items-center");
    expect(appShellSource).not.toContain("relative flex h-[72px] items-center border-b");
    expect(appShellSource).toContain("min-[900px]:grid-cols-[232px_minmax(0,1fr)]");
    expect(appShellSource).toContain("relative z-40 hidden h-dvh min-h-0 border-r");
    expect(appShellSource).toContain('sidebarCollapsed ? "w-[56px] overflow-visible" : "w-[232px] overflow-visible"');
    expect(appShellSource).not.toContain('sidebarCollapsed ? "w-[56px] overflow-visible" : "w-[232px] overflow-hidden"');
    expect(appShellSource).not.toContain("min-[900px]:grid-cols-[184px_minmax(0,1fr)]");
    expect(appShellSource).not.toContain("relative hidden h-dvh min-h-0 overflow-visible");
    expect(appShellSource).toContain("app-sidebar-collapse-rail");
    expect(appShellSource).toContain("app-sidebar-collapse-button");
    expect(appShellSource).toContain("absolute inset-y-0 right-[-10px]");
    expect(appShellSource).toContain("cursor-pointer");
    expect(appShellSource).toContain("app-sidebar-collapse-button pointer-events-none grid h-8 w-8");
    expect(appShellSource).toContain('aria-label={sidebarCollapsed ? tApp("shell.sidebarExpand") : tApp("shell.sidebarCollapse")}');
    expect(appShellSource).toContain("group-hover:opacity-100");
    expect(appShellSource).not.toContain("app-sidebar-collapse-hitbox");
    expect(appShellSource).not.toContain("app-sidebar-resizer");
    expect(appShellSource).not.toContain("MoveHorizontal");
    expect(appShellSource).toContain("group/sidebar-nav-item relative grid min-h-9 w-full min-w-0 overflow-hidden");
    expect(appShellSource).toContain('<span className={cn("min-w-0 truncate", sidebarCollapsed && "sr-only")}>{label}</span>');
    expect(appShellSource).toContain("contentScrollerRef");
    expect(appShellSource).toContain("activeSectionIsCreativeWorkspace");
    expect(appShellSource).toContain("overflow-hidden p-0");
    expect(appShellSource).not.toContain("sticky top-0");
    expect(appShellSource).not.toContain("activeSectionSubtitle");
  });

  it("adds a compact app language switcher to the console sidebar", async () => {
    const source = await readFile(appPath, "utf8");
    const switcherSource = source.slice(source.indexOf("function AppLanguageSwitcher"), source.indexOf("function AccountMenu"));

    expect(source).toContain("Globe2");
    expect(switcherSource).toContain("app-language-switcher");
    expect(switcherSource).toContain("app-language-menu");
    expect(switcherSource).toContain('collapsed ? "mx-auto" : "min-w-0"');
    expect(switcherSource).toContain("grid-cols-[26px_minmax(0,1fr)]");
    expect(switcherSource).toContain('{!collapsed ? <span className="min-w-0 truncate">{getLocaleMeta(currentLocale).label}</span> : null}');
    expect(switcherSource).toContain("bottom-[calc(100%+8px)] left-0 top-auto");
    expect(switcherSource).toContain("supportedLocales.map");
    expect(switcherSource).toContain("getLocaleMeta(locale).label");
    expect(switcherSource).toContain("clientLocaleStorageKey");
    expect(switcherSource).toContain("i18n.changeLanguage(locale)");
    expect(switcherSource).toContain("window.localStorage.setItem");
    expect(switcherSource).toContain("closeOnOutsideClick");
    expect(switcherSource).toContain("closeOnEscape");
    expect(switcherSource).toContain('const languageChangeLabel = i18n.t("common:language.change", { lng: currentLocale });');
    expect(switcherSource).toContain("aria-label={languageChangeLabel}");
    expect(switcherSource).toContain("title={languageChangeLabel}");
    expect(switcherSource).toContain("aria-current={locale === currentLocale ? \"true\" : undefined}");
    expect(source).toContain('{tApp("shell.tagline")}');
    expect(source).toContain("const label = tApp(`navigation.${labelKey}`);");
  });
});
