import { readFile } from "node:fs/promises";

import { describe, expect, it } from "vitest";

const appPath = "src/client/App.tsx";

describe("video creation layout source", () => {
  it("renders video creation as product library plus operation workspace instead of a top control bar", async () => {
    const source = await readFile(appPath, "utf8");
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductComposerReferenceTray"));

    expect(composerSource).toContain("video-workspace-shell");
    expect(composerSource).toContain("h-[100dvh] max-h-[100dvh] min-h-0 grid-rows-[minmax(0,1fr)]");
    expect(composerSource).toContain("transition-[grid-template-columns] duration-200");
    expect(composerSource).toContain("min-[900px]:grid-cols-[var(--product-library-column-width)_minmax(0,1fr)]");
    expect(composerSource).toContain('style={{ "--product-library-column-width": `${productLibraryColumnWidth}px` } as CSSProperties}');
    expect(composerSource).toContain("PRODUCT_LIBRARY_DEFAULT_WIDTH");
    expect(composerSource).toContain("PRODUCT_LIBRARY_COLLAPSED_WIDTH");
    expect(composerSource).not.toContain("PRODUCT_LIBRARY_COLLAPSE_SNAP_WIDTH");
    expect(composerSource).not.toContain("PRODUCT_LIBRARY_MIN_WIDTH");
    expect(composerSource).not.toContain("PRODUCT_LIBRARY_MAX_WIDTH");
    expect(composerSource).not.toContain("min-[900px]:grid-cols-[292px_minmax(0,1fr)]");
    expect(composerSource).toContain("productLibraryCollapsed");
    expect(composerSource).toContain("productLibraryColumnWidth");
    expect(composerSource).not.toContain("const [productLibraryWidth");
    expect(composerSource).not.toContain("handleProductLibraryResizeStart");
    expect(composerSource).not.toContain("handleProductLibraryResizeKeyDown");
    expect(composerSource).not.toContain('role="separator"');
    expect(composerSource).not.toContain('aria-orientation="vertical"');
    expect(composerSource).not.toContain("aria-valuenow={productLibraryColumnWidth}");
    expect(composerSource).toContain("video-product-library-collapse-rail");
    expect(composerSource).toContain("video-product-library-collapse-button");
    expect(composerSource).toContain("transition-[left,color]");
    expect(composerSource).not.toContain("video-product-library-resizer");
    expect(composerSource).not.toContain("productLibraryResizing");
    expect(composerSource).not.toContain("setProductLibraryResizing");
    expect(composerSource).not.toContain("MoveHorizontal");
    expect(composerSource).toContain("cursor-pointer");
    expect(composerSource).toContain("opacity-0");
    expect(composerSource).toContain("group-hover:opacity-100");
    expect(composerSource).toContain('aria-label={productLibraryCollapsed ? "展开商品库" : "折叠商品库"}');
    expect(composerSource).toContain('title={productLibraryCollapsed ? "展开商品库" : "折叠商品库"}');
    expect(composerSource).toContain("onClick={() => setProductLibraryCollapsed((collapsed) => !collapsed)}");
    expect(composerSource).not.toContain("拖动调整商品库宽度");
    expect(composerSource).toContain("video-product-library-column");
    expect(composerSource).toContain("video-operation-column");
    expect(composerSource).toContain("grid content-start gap-3");
    expect(composerSource).not.toContain("grid min-h-full content-start gap-3");
    expect(composerSource).toContain("video-generation-controls compact-generation-controls");
    expect(composerSource).toContain("py-2");
    expect(composerSource).toContain("model-scheme-control");
    expect(composerSource).toContain("model-scheme-chip-row");
    expect(composerSource).toContain("min-[1180px]:col-span-6");
    expect(composerSource).toContain("overflow-visible");
    expect(composerSource).toContain("ModelSchemeChip");
    expect(composerSource).toContain("{schemeSummary}");
    expect(composerSource).toContain('label="视频分辨率"');
    expect(composerSource).toContain("videoResolutionOptions");
    expect(composerSource).toContain("videoResolutionLabel");
    expect(composerSource).toContain("selectedVideoResolution");
    expect(composerSource).toContain("onVideoResolutionChange");
    expect(composerSource).toContain('const languageOptions: FinalVideoLanguage[] = ["ja", "zh", "en"]');
    expect(source).toContain('if (value === "en") return "英语";');
    expect(composerSource).toContain('density="compact"');
    expect(composerSource).toContain("generation-status-message");
    expect(composerSource).toContain("video-generate-summary");
    expect(composerSource).toContain("{generateVideoSummary}");
    expect(composerSource).toContain("tracking-0");
    expect(composerSource).toContain("whitespace-normal");
    expect(composerSource).toContain("break-words");
    expect(composerSource).not.toContain("video-generate-summary min-w-0 truncate");
    expect(composerSource).not.toContain("generateVideoSummaryItems.map");
    expect(composerSource).not.toContain("video-generate-summary-item");
    expect(composerSource).not.toContain("video-generate-summary-separator");
    expect(composerSource).not.toContain("gap-x-2 gap-y-1");
    expect(composerSource).toContain("video-generate-status-center");
    expect(composerSource).toContain("justify-center text-center");
    expect(composerSource).toContain("min-[900px]:grid-cols-[minmax(0,1fr)_minmax(220px,auto)_minmax(220px,320px)]");
    expect(composerSource).not.toContain("subtitle={generateVideoSummary}");
    expect(composerSource).not.toContain("model-scheme-summary min-w-0 whitespace-normal break-words");
    expect(composerSource).not.toContain("model-scheme-summary min-w-0 truncate");
    expect(composerSource).not.toContain("<div className=\"min-w-0 truncate text-xs font-bold text-[var(--muted)]\">{schemeSummary}</div>");
    expect(composerSource).toContain("resolution: selectedVideoResolution");
    expect(composerSource).toContain("ProductCreationProductLibrary");
    expect(composerSource).toContain("ProductCreationOperationWorkspace");
    expect(composerSource).toContain("collapsed={productLibraryCollapsed}");
    expect(composerSource).toContain("productLibrarySearchQuery");
    expect(composerSource).toContain("filterProductLibraryProducts(productOptions, productLibrarySearchQuery");
    expect(composerSource).toContain("product-library-search");
    expect(composerSource).toContain('aria-label="搜索商品"');
    expect(composerSource).toContain('placeholder="搜索商品"');
    expect(composerSource).not.toContain("搜索商品 / SKU");
    expect(composerSource).toContain("product-library-scroll min-h-0 overflow-y-auto");
    expect(composerSource).toContain("没有匹配的商品");
    expect(composerSource).toContain("清空搜索");
    expect(composerSource).not.toContain("手动填写或粘贴商品资料");
    expect(composerSource).not.toContain("footer={");
    expect(composerSource).not.toContain("product-control-bar");
    expect(composerSource).not.toContain("video-parameter-row grid");
    expect(composerSource).not.toContain("<ProductCreationProductPicker");

    const generateBarIndex = composerSource.indexOf("video-generate-bar");
    const historyPanelIndex = composerSource.indexOf("<VideoHistoryPanel");
    expect(generateBarIndex).toBeGreaterThan(-1);
    expect(historyPanelIndex).toBeGreaterThan(-1);
    expect(generateBarIndex).toBeLessThan(historyPanelIndex);
  });

  it("keeps concrete model names in the model scheme summary instead of inline panels", async () => {
    const source = await readFile(appPath, "utf8");
    const composerSource = source.slice(source.indexOf("function ProductCreationComposer"), source.indexOf("function ProductComposerReferenceTray"));
    const referenceTraySource = source.slice(source.indexOf("function ProductComposerReferenceTray"), source.indexOf("function StoryboardComposerPanel"));
    const storyboardPanelSource = source.slice(source.indexOf("function StoryboardComposerPanel"), source.indexOf("function VideoHistoryPanel"));

    expect(composerSource).toContain("model-scheme-chip-row");
    expect(composerSource).toContain('{ label: "文", value: modelConfigChoiceLabel(selectedTextModelConfigId, textModelOptions) }');
    expect(composerSource).toContain('{ label: "图", value: modelConfigChoiceLabel(selectedImageModelConfigId, imageModelOptions) }');
    expect(composerSource).toContain('{ label: "视", value: modelConfigChoiceLabel(selectedVideoModelConfigId, videoModelOptions) }');
    expect(composerSource).not.toContain("textModelLabel={modelConfigChoiceLabel");
    expect(referenceTraySource).not.toContain("图片模型");
    expect(referenceTraySource).not.toContain("modelConfigChoiceLabel(selectedImageModelConfigId");
    expect(referenceTraySource).not.toContain("selectedImageModelConfigId");
    expect(referenceTraySource).not.toContain("imageModelOptions");
    expect(storyboardPanelSource).not.toContain("文本模型:");
    expect(storyboardPanelSource).not.toContain("textModelLabel");
  });

  it("moves account controls into the left navigation shell and keeps video content full bleed", async () => {
    const source = await readFile(appPath, "utf8");
    const appShellSource = source.slice(source.indexOf("<main"), source.indexOf("function AccountMenu"));

    expect(appShellSource).toContain("app-sidebar-account");
    expect(appShellSource).toContain("relative flex h-[72px] items-center");
    expect(appShellSource).not.toContain("relative flex h-[72px] items-center border-b");
    expect(appShellSource).toContain("app-sidebar-collapse-rail");
    expect(appShellSource).toContain("app-sidebar-collapse-button");
    expect(appShellSource).toContain("absolute inset-y-0 right-[-10px]");
    expect(appShellSource).toContain("cursor-pointer");
    expect(appShellSource).toContain("app-sidebar-collapse-button pointer-events-none grid h-8 w-8");
    expect(appShellSource).toContain('aria-label={sidebarCollapsed ? "展开侧边栏" : "折叠侧边栏"}');
    expect(appShellSource).toContain("group-hover:opacity-100");
    expect(appShellSource).not.toContain("app-sidebar-collapse-hitbox");
    expect(appShellSource).not.toContain("app-sidebar-resizer");
    expect(appShellSource).not.toContain("MoveHorizontal");
    expect(appShellSource).toContain("contentScrollerRef");
    expect(appShellSource).toContain('activeSection === "video"');
    expect(appShellSource).toContain("overflow-hidden p-0");
    expect(appShellSource).not.toContain("sticky top-0");
    expect(appShellSource).not.toContain("activeSectionSubtitle");
  });
});
